{
 "title": "NDAC Radio FM Alarms Active Dashboard",
 "description": "NDAC Radio FM Active alarms dashboard",
 "tags": [
  "ActiveAlarmDashboard",
  "RadioAlarms"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "grafana-opensearch-datasource" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "apid",
    "label": "Access Point ID",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data_source.dn.keyword\", \"query\":\"fm_data_source.nhg_alias.keyword:$nhgname\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "NDAC FM ACTIVE ALARMS DASHBOARD",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Critical Alarms",
   "type": "stat",
   "description": "Provides the count of critical alarms",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:critical",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Major Alarms",
   "type": "stat",
   "description": "Provides the count of major alarms",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Major",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:major",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Minor Alarms",
   "type": "stat",
   "description": "Provides the count of minor alarms",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:minor",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Warning Alarms",
   "type": "stat",
   "description": "Provides the count of warning alarms",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:warning",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Service Impacting Alarms",
   "type": "table",
   "description": "This table will show all alarms history across all edges enodeB's",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid  AND ((fm_data.specific_problem:6825) OR (fm_data.specific_problem:7655) OR (fm_data.specific_problem:61631))",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": " Critical Active Alarms",
   "type": "table",
   "description": "This table will show all active alarms that are critical across all edges enodeB's\n\nNote: Turnoff the refresh timer when moving to different page.",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:critical",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": " Major Active Alarms",
   "type": "table",
   "description": "This table will show all active alarms that are major across all edges enodeB's\n\nNote: Turnoff the refresh timer when moving to different page.",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:major",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": " Minor Active Alarms",
   "type": "table",
   "description": "This table will show all active alarms that are minor across all edges enodeB's\n\nNote: Turnoff the refresh timer when moving to different page.",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:minor",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": " Warning Active Alarms",
   "type": "table",
   "description": "This table will show all active alarms that are warning across all edges enodeB's\n\nNote: Turnoff the refresh timer when moving to different page.",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:warning",
     "timeField": "fm_data.event_time"
    }
   ]
  }
 ]
}