{
 "title": "NDAC Application Alarms History Dashboard",
 "description": "NDAC Application History alarms dashboard",
 "tags": [
  "ApplAlarms",
  "ApplHistoryAlarms"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "grafana-opensearch-datasource" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data.severity.keyword\"}"
   },
   {
    "name": "alarmstate",
    "label": "Alarm State",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data.alarm_state.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "NDAC APPLICATION HISTORY ALARMS DASHBOARD",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Critical Alarms",
   "type": "stat",
   "description": "Provides the count of critical alarms",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:CRITICAL AND fm_data.alarm_state:$alarmstate",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Major Alarms",
   "type": "stat",
   "description": "Provides the count of major alarms",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:MAJOR AND fm_data.alarm_state:$alarmstate",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Minor Alarms",
   "type": "stat",
   "description": "Provides the count of minor alarms",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:MINOR AND fm_data.alarm_state:$alarmstate",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Warning Alarms",
   "type": "stat",
   "description": "Provides the count of warning alarms",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:WARNING AND fm_data.alarm_state:$alarmstate",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Cleared Alarms",
   "type": "stat",
   "description": "Provides the count of cleared alarms",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.alarm_state.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.alarm_state:CLEARED",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Active Alarms",
   "type": "stat",
   "description": "Provides the count of active alarms",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.alarm_state.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.alarm_state:ACTIVE",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "History Alarms",
   "type": "table-old",
   "description": "This table will show all alarms history across all edges enodeB's",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:$severity AND fm_data.alarm_state:$alarmstate",
     "timeField": "fm_data.event_time"
    }
   ]
  }
 ]
}