{
 "title": "Nokia DAC IXR PM KPI",
 "tags": [ "IXRPM" ],
 "time": { "from": "now-12h", "to": "now-15m" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "grafana-opensearch-datasource" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\":\"pm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "slice",
    "label": "Slice ID",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.edge_alias.keyword\", \"query\":\"pm_data_source.nhg_alias.keyword:$nhgname\"}"
   },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "5m,15m,1h,3h,6h,12h,1d,7d,15d,1M"
   },
   {
    "name": "bgp_dn_filter",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.dn.keyword\",\n\"query\":\"pm_data_source.edge_alias.keyword:$slice\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Firmware Version",
   "type": "table",
   "description": "This KPI shows the firmware version",
   "gridPos": { "h": 4, "w": 12, "x": 5, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.edge_alias.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pm_data_source.additional_data.version_number.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_firmware_version_value",
       "hide": true,
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data.ndac_rr_ixr_firmware_version_value:* AND pm_data_source.nhg_alias.keyword:$nhgname",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  { "title": "Port Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "IXR Statistics Per Port",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.dn.keyword", "id": "2", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
      { "field": "pm_data_source.timestamp", "id": "7", "settings": { "order": "desc", "orderBy": "_term", "size": "1" }, "type": "terms" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_state_oper_state",
       "id": "1",
       "settings": {},
       "type": "max"
      },
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_in_packets_rate",
       "id": "3",
       "type": "avg"
      },
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_out_packets_rate",
       "id": "4",
       "type": "avg"
      },
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_in_octets_rate",
       "id": "5",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_out_octets_rate",
       "id": "6",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_in_errors_rate",
       "id": "8",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_out_errors_rate",
       "id": "9",
       "type": "avg"
      },
      {
       "field": "pm_data.ndac_rr_ixr_port_oper_state_oper_state",
       "id": "10",
       "type": "max"
      },
      {
       "field": "pm_data.ndac_rr_ixr_port_admin_state_admin_state",
       "id": "11",
       "type": "max"
      },
      {
       "field": "pm_data.ndac_rr_ixr_port_oper_state_change_count_oper_state_change_count",
       "id": "12",
       "type": "max"
      }
     ],
     "query": "pm_data_source.dn.keyword:*PORT* AND pm_data_source.dn.keyword:*SOURCE* AND pm_data_source.edge_alias.keyword:$slice",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Port Status",
   "type": "timeseries",
   "description": "This KPI shows the physical port status",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_state_oper_state",
       "hide": false,
       "id": "3",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.dn.keyword:*PORT* AND pm_data_source.edge_alias.keyword:$slice AND pm_data.ndac_rr_ixr_port_state_oper_state:*",
     "timeField": "pm_data_source.timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_oper_state_oper_state",
       "hide": false,
       "id": "3",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.dn.keyword:*PORT* AND pm_data_source.edge_alias.keyword:$slice AND pm_data.ndac_rr_ixr_port_oper_state_oper_state:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Port Admin State",
   "type": "timeseries",
   "description": "This KPI shows the port admin state",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_admin_state_admin_state",
       "hide": false,
       "id": "3",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.dn.keyword:*PORT* AND pm_data_source.edge_alias.keyword:$slice AND pm_data.ndac_rr_ixr_port_admin_state_admin_state:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "In Data Rate",
   "type": "timeseries",
   "description": "This KPI shows the port inbound data rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_in_octets_rate",
       "hide": false,
       "id": "3",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "pm_data.ndac_rr_ixr_port_stats_in_octets_rate:* AND pm_data_source.dn.keyword:*PORT* AND pm_data_source.edge_alias.keyword:$slice",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Out Data Rate",
   "type": "timeseries",
   "description": "This KPI shows the port outbound data rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_out_octets_rate",
       "id": "3",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "pm_data.ndac_rr_ixr_port_stats_out_octets_rate:* AND pm_data_source.dn.keyword:*PORT* AND pm_data_source.edge_alias.keyword:$slice",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "In Packets Rate",
   "type": "timeseries",
   "description": "This KPI shows the port inbound packet rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_in_packets_rate",
       "hide": false,
       "id": "3",
       "type": "avg"
      }
     ],
     "query": "pm_data.ndac_rr_ixr_port_stats_in_packets_rate:* AND pm_data_source.edge_alias.keyword:$slice AND pm_data_source.dn.keyword:*PORT*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Out Packets Rate",
   "type": "timeseries",
   "description": "This KPI shows the port outbound packet rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_out_packets_rate",
       "hide": false,
       "id": "3",
       "type": "avg"
      }
     ],
     "query": "pm_data.ndac_rr_ixr_port_stats_out_packets_rate:* AND pm_data_source.dn.keyword:*PORT* AND pm_data_source.edge_alias.keyword:$slice",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "In Errors Rate",
   "type": "timeseries",
   "description": "This KPI shows the port inbound error rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_in_errors_rate",
       "hide": false,
       "id": "3",
       "type": "avg"
      }
     ],
     "query": "pm_data.ndac_rr_ixr_port_stats_in_errors_rate:* AND pm_data_source.edge_alias.keyword:$slice AND pm_data_source.dn.keyword:*PORT*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Out Errors Rate",
   "type": "timeseries",
   "description": "This KPI shows the port outbound error rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_stats_out_errors_rate",
       "hide": false,
       "id": "3",
       "type": "avg"
      }
     ],
     "query": "pm_data.ndac_rr_ixr_port_stats_out_errors_rate:* AND pm_data_source.edge_alias.keyword:$slice AND pm_data_source.dn.keyword:*PORT*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Port Oper State Changed Time",
   "type": "table",
   "description": "This KPI shows the timestamp of last time when port changed its operating state ",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 62 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pm_data_source.additional_data.oper_state_last_changed",
       "id": "8",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_port_last_state_change",
       "hide": false,
       "id": "3",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.dn.keyword:*PORT* AND pm_data_source.edge_alias.keyword:$slice AND pm_data.ndac_rr_ixr_port_last_state_change:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "VRF Interface State",
   "type": "bargauge",
   "description": "This KPI shows the Operational State of an L3 interface for each VPRN(VRF)",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_ixr_vrf_iface_oper_state_oper_state",
       "id": "3",
       "type": "max"
      }
     ],
     "query": "pm_data_source.dn.keyword:*IFACE* AND pm_data_source.edge_alias.keyword:$slice AND pm_data.ndac_rr_ixr_vrf_iface_oper_state_oper_state:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "GNSS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync State",
     "type": "stat",
     "description": "This KPI shows the GNSS sync state",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_gnss_sync_state_sync_status",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_gnss_sync_state_sync_status:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Antenna State",
     "type": "stat",
     "description": "This KPI shows the GNSS antenna state",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_gnss_antenna_state_antenna_status",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_gnss_antenna_state_antenna_status:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Receiver State",
     "type": "stat",
     "description": "This KPI shows the GNSS receiver state",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_gnss_receiver_state_receiver_status",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_gnss_receiver_state_receiver_status:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Available Satellite",
     "type": "stat",
     "description": "This KPI shows the current available satellite count",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_gnss_avail_sat_count_visible_satellite_count",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_gnss_avail_sat_count_visible_satellite_count:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Used Satellite",
     "type": "stat",
     "description": "This KPI shows the used current satellite count",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_gnss_used_sat_count_used_satellite_count",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_gnss_used_sat_count_used_satellite_count:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Available Satellite Count",
     "type": "timeseries",
     "description": "This KPI shows the available satellite count",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_gnss_avail_sat_count_visible_satellite_count",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_gnss_avail_sat_count_visible_satellite_count:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Used Satellite Count",
     "type": "timeseries",
     "description": "This KPI shows the used satellite count",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_gnss_used_sat_count_used_satellite_count",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_gnss_used_sat_count_used_satellite_count:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "BGP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "BGP Neighbor State",
     "type": "bargauge",
     "description": "This KPI shows the BGP session state for each neighbor in each VPRN",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_bgp_vprn_neighbor_state_session_state",
         "id": "3",
         "type": "max"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_bgp_vprn_neighbor_state_session_state:* AND pm_data_source.edge_alias.keyword:$slice AND pm_data_source.dn:$bgp_dn_filter ",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "BGP Neighbor Stats",
     "type": "timeseries",
     "description": "This KPI shows the BGP session state for each neighbor in each VPRN",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 71 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_bgp_vprn_neighbor_state_session_state",
         "id": "3",
         "type": "max"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_bgp_vprn_neighbor_state_session_state:* AND pm_data_source.edge_alias.keyword:$slice AND pm_data_source.dn:$bgp_dn_filter ",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "BGP Prefix Active Stats",
     "type": "timeseries",
     "description": "This KPI shows the BGP Prefix Active Stats",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_bgp_pfx_stats_active",
         "id": "3",
         "type": "max"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_bgp_pfx_stats_active:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "BGP Prefix Backup Stats",
     "type": "timeseries",
     "description": "This KPI shows the BGP Prefix Backup Stats over last 5 min",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_bgp_pfx_stats_backup",
         "id": "3",
         "type": "max"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_bgp_pfx_stats_backup:* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "BGP Prefix Sent Stats",
     "type": "timeseries",
     "description": "This KPI shows the BGP Prefix Sent Stats over last 5 min",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_bgp_pfx_stats_sent",
         "id": "3",
         "type": "max"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_bgp_pfx_stats_sent:* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "BGP Prefix Received Stats",
     "type": "timeseries",
     "description": "This KPI shows the BGP Prefix Received Stats over last 5 min",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_bgp_pfx_stats_received",
         "id": "3",
         "type": "max"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_bgp_pfx_stats_received:* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "BGP Prefix Rejected Stats",
     "type": "timeseries",
     "description": "This KPI shows the BGP Prefix Rejected Stats over last 5 min",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_bgp_pfx_stats_rejected",
         "id": "3",
         "type": "max"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_bgp_pfx_stats_rejected:* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "BGP Prefix Supressed Stats",
     "type": "timeseries",
     "description": "This KPI shows the BGP Prefix Supressed Stats over last 5 min",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 113 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_bgp_pfx_stats_suppressed",
         "id": "3",
         "type": "max"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_bgp_pfx_stats_suppressed:* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Power Supply Unit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "PSU Status",
     "type": "table",
     "description": "This KPI shows the Power Supply Unit Status",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "order": "desc", "orderBy": "_term", "size": "1" }, "type": "terms" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_chassis_psu_ac_ac_status",
         "id": "3",
         "type": "max"
        },
        {
         "field": "pm_data.ndac_rr_ixr_chassis_psu_dc_dc_status",
         "id": "5",
         "type": "max"
        },
        {
         "field": "pm_data.ndac_rr_ixr_chassis_psu_input_input_status",
         "id": "6",
         "type": "max"
        },
        {
         "field": "pm_data.ndac_rr_ixr_chassis_psu_output_output_status",
         "id": "7",
         "type": "max"
        },
        {
         "field": "pm_data.ndac_rr_ixr_chassis_psu_temp_temp_status",
         "id": "8",
         "type": "max"
        }
       ],
       "query": "pm_data_source.dn.keyword:*POWSUID* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "BFD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "BFD Session Current Status",
     "type": "table",
     "description": "This KPI shows the status of BFD session",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        {
         "field": "pm_data_source.timestamp",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_bfd_state_oper_state",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.edge_alias.keyword:$slice AND pm_data.ndac_rr_ixr_bfd_state_oper_state:*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "BFD Session Status",
     "type": "timeseries",
     "description": "This KPI shows the status of BFD session",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_bfd_state_oper_state",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.edge_alias.keyword:$slice AND pm_data.ndac_rr_ixr_bfd_state_oper_state:*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "LLDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "LLDP Neighbours",
     "type": "table",
     "description": "This KPI shows the LLDP Neighbours",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_data"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_lldp_neighbors_remote_index_value:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "SFP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "SFP Temperature",
     "type": "timeseries",
     "description": "This KPI shows the SFP Temperature",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_port_sfp_temperature_current",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_port_sfp_temperature_current:* AND pm_data_source.edge_alias.keyword:$slice AND pm_data_source.dn.keyword:*PORT*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "SFP Rx Level",
     "type": "timeseries",
     "description": "This KPI shows the SFP Rx Level",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_port_sfp_rx_level_current",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_port_sfp_rx_level_current:* AND pm_data_source.edge_alias.keyword:$slice AND pm_data_source.dn.keyword:*PORT*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "SFP Tx Level",
     "type": "timeseries",
     "description": "This KPI shows the SFP Tx Level",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pm_data_source.dn.keyword", "id": "4", "settings": { "order": "desc", "orderBy": "_term", "size": "0" }, "type": "terms" },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_port_sfp_tx_level_current",
         "hide": false,
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_port_sfp_tx_level_current:* AND pm_data_source.edge_alias.keyword:$slice AND pm_data_source.dn.keyword:*PORT*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "This KPI shows the CPU usage for the last 60 seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.edge_alias.keyword",
         "id": "3",
         "settings": { "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_cpu_usage_60_cpu_usage",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "System Used Memory",
     "type": "timeseries",
     "description": "This KPI shows the memory used by the system",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.edge_alias.keyword",
         "id": "3",
         "settings": { "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_sys_used_mem_total_in_use",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "System Available Memory",
     "type": "timeseries",
     "description": "This KPI shows the available memory in the system",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.edge_alias.keyword",
         "id": "2",
         "settings": { "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "3", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_sys_avail_mem_available_memory",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Used Flash Space Percentage",
     "type": "timeseries",
     "description": "This KPI shows the used flash space percentage in the system",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.edge_alias.keyword",
         "id": "2",
         "settings": { "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "3", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_flash_used_percent_percent_used",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_flash_used_percent_percent_used:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Free Flash Space",
     "type": "timeseries",
     "description": "This KPI shows the available flash space in the system",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.edge_alias.keyword",
         "id": "2",
         "settings": { "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "3", "settings": { "interval": "$agg", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "field": "pm_data.ndac_rr_ixr_flash_free_space_free_space",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "hide": false,
         "id": "4",
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "1" }
         ],
         "settings": { "script": "params.var1" },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data.ndac_rr_ixr_flash_free_space_free_space:* AND pm_data_source.edge_alias.keyword:$slice",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  }
 ]
}