{
 "title": "Nokia DAC Radio 5G PM KPI - Slice Performance 5G035",
 "tags": [ "Radio5G" ],
 "time": { "from": "now-24h", "to": "now-15m" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "grafana-opensearch-datasource" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "slice_id",
    "label": "Slice ID",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.slice_id.keyword\", \"query\":\"pm_data_source.nhg_alias.keyword:$nhgname\", \"size\": 10000}"
   },
   {
    "name": "groupby",
    "label": "Object Level",
    "query": "gNB : pm_data_source.hw_id.keyword, Cell : pm_data_source.dn.keyword"
   },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "15m,30m,1h,3h,6h,12h,1d,7d,15d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Admission control per slice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NR_5207a 5G SA Number of non-GBR DRB radio admission requests for SA user, per PLMN, per slice / nonGBR DRB AC req PLMN slice [#]",
   "type": "timeseries",
   "description": "This KPI shows the non-GBR DRB radio admission requests for SA user, for the given slice and PLMN.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.NSL_M55149C00002",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.NSL_M55149C00002",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "hide": false,
       "id": "6",
       "meta": {},
       "pipelineVariables": [
        { "name": "am55149c00002", "pipelineAgg": "3" },
        { "name": "m55149c00002", "pipelineAgg": "4" }
       ],
       "settings": {
        "script": "if (params.am55149c00002 == null) {return null} else {return params.m55149c00002}"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NSL_M55149C00002:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "NR_5208a 5G SA Non-GBR DRB admission control success ratio for SA user, per PLMN, per slice / nonGBR DRB AC SR PLMN slice [%]",
   "type": "timeseries",
   "description": "This KPI shows the success ratio of non-GBR DRB radio admission for SA user, for the given slice and PLMN.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.NSL_M55149C00002",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.NSL_M55149C00002",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.NSL_M55149C00003",
       "hide": true,
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "6",
       "meta": {},
       "pipelineVariables": [
        { "name": "am55149c00002", "pipelineAgg": "3" },
        { "name": "m55149c00002", "pipelineAgg": "4" },
        { "name": "m55149c00003", "pipelineAgg": "5" }
       ],
       "settings": {
        "script": "if (params.am55149c00002 == null) {return null} else if(params.m55149c00002 == 0) {return 0} else {return (100*(params.m55149c00003)/(params.m55149c00002))}"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NSL_M55149C00002:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "NR_1295a 5G SA Number of number of GBR DRBs radio admission requests for SA user per slice / SA GBR DRB AC req slice\t[#]",
   "type": "timeseries",
   "description": "This KPI shows the number of GBR DRB radio admission requests for SA user, for the given slice.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.NSL_M55149C01001",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.NSL_M55149C01001",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "6",
       "meta": {},
       "pipelineVariables": [
        { "name": "am55149c01001", "pipelineAgg": "3" },
        { "name": "m55149c01001", "pipelineAgg": "4" }
       ],
       "settings": {
        "script": "if (params.am55149c01001 == null) {return null} else {return (params.m55149c01001)}"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NSL_M55149C01001:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "NR_1296a 5G SA Radio admission success ratio of GBR DRBs per slice / SA GBR DRB AC SR slice [%]",
   "type": "timeseries",
   "description": "This KPI shows the success ratio of radio admission of GBR DRBs for SA user, per slice.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.NSL_M55149C01001",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.NSL_M55149C01001",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.NSL_M55149C01002",
       "hide": true,
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "6",
       "meta": {},
       "pipelineVariables": [
        { "name": "am55149c01001", "pipelineAgg": "3" },
        { "name": "m55149c01001", "pipelineAgg": "4" },
        { "name": "m55149c01002", "pipelineAgg": "5" }
       ],
       "settings": {
        "script": "if (params.am55149c01001 == null) {return null} else if(params.m55149c01001 == 0) {return 0} else {return (100*(params.m55149c01002)/(params.m55149c01001))}"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NSL_M55149C01001:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "DRB setup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "NR_1297a 5G SA GBR DRB setup success ratio per slice / SA GBR DRB stp SR slice [%]",
     "type": "timeseries",
     "description": "This KPI shows the success ratio of establishing a GBR DRB on CU upon successful PDU session establishment or modification, for SA user, per slice.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "$groupby",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.NSL_M55149C01001",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "pm_data.NSL_M55149C01001",
         "hide": true,
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "pm_data.NSL_M55149C01003",
         "hide": true,
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "select field",
         "id": "6",
         "meta": {},
         "pipelineVariables": [
          { "name": "am55149c01001", "pipelineAgg": "3" },
          { "name": "m55149c01001", "pipelineAgg": "4" },
          { "name": "m55149c01003", "pipelineAgg": "5" }
         ],
         "settings": {
          "script": "if (params.am55149c01001 == null) {return null} else if(params.m55149c01001 == 0) {return 0} else {return (100*(params.m55149c01003)/(params.m55149c01001))}"
         },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NSL_M55149C01001:*",
       "timeField": "pm_data_source.end_timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Data volume per slice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "NR_5136a 5G SA PDCP SDU transmitted data volume in downlink per slice / PDCP SDU vol DL slice [MB]",
     "type": "timeseries",
     "description": "This KPI shows the PDCP SDU data volume transmitted via gNB in downlink direction for the given Slice and PLMN. Discarded DL PDCP SDUs are not counted.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "$groupby",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.NPSL_M55328C00003",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "pm_data.NPSL_M55328C00003",
         "hide": true,
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "hide": false,
         "id": "5",
         "pipelineVariables": [
          { "name": "am55328c00003", "pipelineAgg": "3" },
          { "name": "m55328c00003", "pipelineAgg": "4" }
         ],
         "settings": {
          "script": "if (params.am55328c00003 == null) {return null} else {return (params.m55328c00003)/1000}"
         },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NPSL_M55328C00003:*",
       "timeField": "pm_data_source.end_timestamp"
      }
     ]
    },
    {
     "title": "NR_5137a 5G SA PDCP SDU received data volume in uplink per slice / PDCP SDU vol UL slice [MB]",
     "type": "timeseries",
     "description": "This KPI shows the PDCP SDU data volume received at gNB in uplink direction for the given Slice and PLMN. Discarded UL PDCP SDUs are not counted.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "$groupby",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.NPSL_M55328C00005",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "pm_data.NPSL_M55328C00005",
         "hide": true,
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "hide": false,
         "id": "5",
         "pipelineVariables": [
          { "name": "am55328c00005", "pipelineAgg": "3" },
          { "name": "m55328c00005", "pipelineAgg": "4" }
         ],
         "settings": {
          "script": "if (params.am55328c00005 == null) {return null} else {return (params.m55328c00005)/1000}"
         },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NPSL_M55328C00005:*",
       "timeField": "pm_data_source.end_timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency per slice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "NR_5138a 5G SA PDCP SDU average delay in downlink per slice / PDCP SDU avg delay DL slice [microsecond]",
     "type": "timeseries",
     "description": "This KPI shows the downlink average delay for PDCP SDUs per slice, calculated as time difference between the reception of the PDCP SDU from NG-U and DL PDCP PDU is sent towards RLC layer.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "$groupby",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.NPSL_M55328C00006",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "pm_data.NPSL_M55328C00006",
         "hide": true,
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "pm_data.NPSL_M55328C00002",
         "hide": true,
         "id": "5",
         "type": "sum"
        },
        {
         "id": "8",
         "pipelineVariables": [
          { "name": "am55328c00006", "pipelineAgg": "3" },
          { "name": "m55328c00006", "pipelineAgg": "4" },
          { "name": "m55328c00002", "pipelineAgg": "5" }
         ],
         "settings": {
          "script": "if (params.am55328c00006 == null) {return null} else if(params.m55328c00002 == 0) {return 0} else {return (params.m55328c00006)/(params.m55328c00002)}"
         },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NPSL_M55328C00006:*",
       "timeField": "pm_data_source.end_timestamp"
      }
     ]
    },
    {
     "title": "NR_5139a 5G SA PDCP SDU average delay in uplink per slice / PDCP SDU avg delay UL slice [microsecond]",
     "type": "timeseries",
     "description": "This KPI shows the uplink average delay for PDCP SDUs per slice, calculated as time difference between reception of UL PDCP PDU from RLC layer, and when the PDCP SDU is sent towards NG-U.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "$groupby",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.NPSL_M55328C00007",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "pm_data.NPSL_M55328C00007",
         "hide": true,
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "pm_data.NPSL_M55328C00004",
         "hide": true,
         "id": "5",
         "type": "sum"
        },
        {
         "id": "8",
         "pipelineVariables": [
          { "name": "am55328c00007", "pipelineAgg": "3" },
          { "name": "m55328c00007", "pipelineAgg": "4" },
          { "name": "m55328c00004", "pipelineAgg": "5" }
         ],
         "settings": {
          "script": "if (params.am55328c00007 == null) {return null} else if(params.m55328c00004 == 0) {return 0} else {return (params.m55328c00007)/(params.m55328c00004)}"
         },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NPSL_M55328C00007:*",
       "timeField": "pm_data_source.end_timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "SA Intra-frequency intra-gNB intra-DU HO per slice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "NR_5210a 5G SA Intra-frequency intra-gNB intra-DU handover success ratio per PLMN, per slice / intraf intraDU HO exe SR PLMN slice [%]",
     "type": "timeseries",
     "description": "This KPI shows the success ratio of intra-frequency intra-gNB intra-DU handover for the given slice and PLMN.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "$groupby",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.NSL_M55149C00005",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "pm_data.NSL_M55149C00005",
         "hide": true,
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "pm_data.NSL_M55149C00004",
         "hide": true,
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "select field",
         "id": "6",
         "meta": {},
         "pipelineVariables": [
          { "name": "am55149c00005", "pipelineAgg": "3" },
          { "name": "m55149c00005", "pipelineAgg": "4" },
          { "name": "m55149c00004", "pipelineAgg": "5" }
         ],
         "settings": {
          "script": "  if (params.am55149c00005 == null) {return null} else if(params.m55149c00004 == 0) {return 0} else {return (params.m55149c00005 * 100)/params.m55149c00004}"
         },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NSL_M55149C00005:*",
       "timeField": "pm_data_source.end_timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "SA Intra-frequency intra-gNB inter-DU HO per slice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "NR_5212a 5G SA Intra-frequency intra-gNB inter-DU handover execution success ratio per PLMN, per slice / intraf inagNB interDU HO exe SR PLMN slice [%]",
     "type": "timeseries",
     "description": "This KPI shows the success ratio of intra-frequency inter-gNB intra-DU handover for the given slice and PLMN.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "$groupby",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.NSL_M55149C00007",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "pm_data.NSL_M55149C00007",
         "hide": true,
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "pm_data.NSL_M55149C00006",
         "hide": true,
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "select field",
         "id": "6",
         "meta": {},
         "pipelineVariables": [
          { "name": "am55149c00007", "pipelineAgg": "3" },
          { "name": "m55149c00007", "pipelineAgg": "4" },
          { "name": "m55149c00006", "pipelineAgg": "5" }
         ],
         "settings": {
          "script": "if (params.am55149c00007 == null) {return null} else if(params.m55149c00006 == 0) {return 0} else {return (params.m55149c00007 * 100)/params.m55149c00006}"
         },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NSL_M55149C00007:*",
       "timeField": "pm_data_source.end_timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "SA Intra-frequency inter-gNB outgoing HO per slice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "NR_5214a 5G SA Intra-frequency inter-gNB outgoing handover execution success ratio per PLMN, per slice / intraf interNB out HO exe SR PLMN slice [%]",
     "type": "timeseries",
     "description": "This KPI shows the success ratio of the intra-frequency inter-gNB outgoing handover for the given slice and PLMN.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "$groupby",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.NSL_M55149C00009",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "pm_data.NSL_M55149C00009",
         "hide": true,
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "pm_data.NSL_M55149C00008",
         "hide": true,
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "select field",
         "id": "6",
         "meta": {},
         "pipelineVariables": [
          { "name": "am55149c00009", "pipelineAgg": "3" },
          { "name": "m55149c00009", "pipelineAgg": "4" },
          { "name": "m55149c00008", "pipelineAgg": "5" }
         ],
         "settings": {
          "script": "if (params.m55149c00009 == null) {return null} else if(params.m55149c00008 == 0) {return 0} else {return (params.m55149c00009 * 100)/params.m55149c00008}"
         },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NSL_M55149C00009:*",
       "timeField": "pm_data_source.end_timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "SA Inter-frequency intra-DU handover per slice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "NR_5215a 5G SA Number of inter-frequency intra-gNB intra-DU handover execution attempts per PLMN, per slice [#]",
     "type": "timeseries",
     "description": "This KPI shows the number of inter-frequency intra-gNB intra-DU handover attempts for the given slice and PLMN.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "$groupby",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.NSL_M55149C00550",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "pm_data.NSL_M55149C00550",
         "hide": true,
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "id": "8",
         "pipelineVariables": [
          { "name": "am55149c00550", "pipelineAgg": "3" },
          { "name": "m55149c00550", "pipelineAgg": "4" }
         ],
         "settings": {
          "script": "if (params.am55149c00550 == null) { return null } else { return params.m55149c00550 }"
         },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NSL_M55149C00550:*",
       "timeField": "pm_data_source.end_timestamp"
      }
     ]
    },
    {
     "title": "NR_5216a 5G SA Inter-frequency intra-gNB intra-DU handover execution success ratio per PLMN, per slice [%]",
     "type": "timeseries",
     "description": "This KPI shows the success ratio of inter-frequency intra-gNB intra-DU handover for the given slice and PLMN.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "$groupby",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.NSL_M55149C00550",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "pm_data.NSL_M55149C00550",
         "hide": true,
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "pm_data.NSL_M55149C00551",
         "hide": true,
         "id": "8",
         "type": "sum"
        },
        {
         "id": "9",
         "pipelineVariables": [
          { "name": "am55149c00550", "pipelineAgg": "3" },
          { "name": "m55149c00550", "pipelineAgg": "4" },
          { "name": "m55149c00551", "pipelineAgg": "8" }
         ],
         "settings": {
          "script": "if ( params.am55149c00550 == null ) { return null } else if ( params.m55149c00550 == 0 ) { return 0 } else { return 100*(params.m55149c00551)/(params.m55149c00550) }"
         },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*SST* AND pm_data.NSL_M55149C00550:*",
       "timeField": "pm_data_source.end_timestamp"
      }
     ]
    }
   ]
  }
 ]
}