{
 "title": "Nokia DAC CORE 5G PM KPI",
 "tags": [ "CorePM" ],
 "time": { "from": "now-24h", "to": "now-15m" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "grafana-opensearch-datasource" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "snssai",
    "label": "SNSSAI",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.dn.keyword\",\n\"query\":\"pm_data_source.nhg_alias.keyword:$nhgname AND  pm_data_source.dn.keyword:*SNSSAI* AND NOT pm_data_source.dn.keyword:*FIVEQI*\"}"
   },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "5m,15m,1h,3h,6h,12h,1d,7d,15d,1M"
   }
  ]
 },
 "panels": [
  {
   "title": "UL Throughput",
   "type": "stat",
   "description": "Uplink Throughput (outbound bitrate on N6 interface)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_5g_dnn_n6_outbound_bitrate",
       "hide": false,
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_5g_dnn_n6_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "DL throughput",
   "type": "stat",
   "description": "Downlink Throughput (outbound bitrate on N3 interface)",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_5g_n3_outbound_bitrate",
       "hide": false,
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_5g_n3_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "UE throughput UL",
   "type": "stat",
   "description": "Overall UE uplink throughput",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_ue_ul_bitrate",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_ue_ul_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "UE throughput DL",
   "type": "stat",
   "description": "Overall UE downlink throughput",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_ue_dl_bitrate",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_ue_dl_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Registered UEs",
   "type": "stat",
   "description": "Current Number of Registered UEs",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_5g_ue_info_rm_registered_ues",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_5g_ue_info_rm_registered_ues:* AND pm_data_source.nhg_alias.keyword:$nhgname",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "3GPP KPI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "AMFMeanRegNbr",
     "type": "timeseries",
     "description": "This KPI describe the mean number of subscribers that are registered to a network slice instance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_amf_mean_reg_nbr",
         "id": "3",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_amf_mean_reg_nbr",
         "id": "3",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "RSR- initialReg",
     "type": "timeseries",
     "description": "This KPI describes the ratio of the number of successfully performed registration procedures to the number of initial registration procedures for the AMF set which related to one single network slice  and is used to evaluate accessibility provided by the end-to-end network slice and network performance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_rsr_initial_reg",
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_rsr_initial_reg",
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "RSR-MobilityReg",
     "type": "timeseries",
     "description": "This KPI describes the ratio of the number of successfully performed registration procedures to the number of attempted mobility procedures for the AMF set which related to one single network slice  and is used to evaluate accessibility provided by the end-to-end network slice  and network performance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "6", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_rsr_mobility_reg",
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "6", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_rsr_mobility_reg",
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "RSR-PeriodicReg",
     "type": "timeseries",
     "description": "This KPI describes the ratio of the number of successfully performed registration procedures to the number of attempted periodic procedures for the AMF set which related to one single network slice  and is used to evaluate accessibility provided by the end-to-end network slice  and network performance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "6", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_rsr_periodic_reg",
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "6", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_rsr_periodic_reg",
         "id": "3",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDUSessionEstSR",
     "type": "timeseries",
     "description": "This KPI describes the ratio of the number of successful PDU session establishment request to the number of PDU session establishment request attempts for 5G network for the SMF which related to one network slice (S-NSSAI) and is used to evaluate accessibility provided by the end-to-end network slice and network performance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pdu_session_est_sr",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pdu_session_est_sr",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "UTSNSI",
     "type": "timeseries",
     "description": "This KPI describes the upstream throughput of one single network slice  by computing the packet size for each successfully received  UL IP packet through the network slice  during each observing granularity period and is used to evaluate integrity performance of the end-to-end network slice .",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "pm_data.ndac_rr_mcn_5g_utsnsi", "id": "1", "type": "avg" }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "pm_data.ndac_rr_mcn_5g_utsnsi", "id": "1", "type": "avg" }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "DTSNSI",
     "type": "timeseries",
     "description": "This KPI describes the downstream throughput of one single network slice instance by computing the packet size for each successfully transmitted DL IP packet through the network slice instance during each observing granularity period and is used to evaluate integrity performance of the end-to-end network slice instance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "pm_data.ndac_rr_mcn_5g_dtsnsi", "id": "1", "type": "avg" }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "pm_data.ndac_rr_mcn_5g_dtsnsi", "id": "1", "type": "avg" }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDUSesMeanNbr",
     "type": "timeseries",
     "description": "This KPI describes the mean number of PDU sessions that are successfully established in a network slice.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pdu_ses_mean_nbr",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pdu_ses_mean_nbr",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDUEstTime",
     "type": "timeseries",
     "description": "This KPI describes the time of successful PDU session establishment which related to one single network slice and is used to evaluate utilization provided by the end-to-end network slice and network performance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pdu_est_time",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pdu_est_time",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Number of initial registration requests",
     "type": "timeseries",
     "description": "This KPI provides the number of initial registration requests received by the AMF over last 5 mins",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_rm_reg_init_req",
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_5g_rm_reg_init_req:*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_rm_reg_init_req",
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_5g_rm_reg_init_req:*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Number of initial registration success",
     "type": "timeseries",
     "description": "This KPI provides the number of successful initial registrations by the AMF over last 5 mins",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}} {{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_rm_reg_init_succ",
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_5g_rm_reg_init_succ:*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "5", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_rm_reg_init_succ",
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_5g_rm_reg_init_succ:*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Number of authentication rejections",
     "type": "timeseries",
     "description": "This KPI provides the number of authentication rejections over last 5 mins",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "6", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_ue_info_ue_auth_failure_num",
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_5g_ue_info_ue_auth_failure_num:*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "6", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_ue_info_ue_auth_failure_num",
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_5g_ue_info_ue_auth_failure_num:*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Number of unsuccessful UE Secondary Authentication Attempts",
     "type": "timeseries",
     "description": "Number of unsuccessful UE Secondary Authentication Attempts per DNN",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "6", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_smf_auth_failed_dnn",
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_5g_smf_auth_failed_dnn:*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "6", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_smf_auth_failed_dnn",
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_5g_smf_auth_failed_dnn:*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Mean number of Framed Routes Established",
     "type": "timeseries",
     "description": "Mean number of Framed Routes Established per DNN",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "6", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_upf_num_framed_routes_dnn",
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_5g_upf_num_framed_routes_dnn:*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "6", "settings": { "interval": "$agg", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_upf_num_framed_routes_dnn",
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_5g_upf_num_framed_routes_dnn:*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "UE throughput DL",
     "type": "timeseries",
     "description": "UE throughput  on downlink",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_ue_dl_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_ue_dl_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "UE throughput UL",
     "type": "timeseries",
     "description": "UE throughput  on uplink",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_ue_ul_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_ue_ul_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "UE throughput - Per IMSI",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 101 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.timestamp",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_ue_ul_rate",
         "id": "1",
         "type": "sum"
        },
        {
         "field": "pm_data.ndac_rr_mcn_5g_ue_dl_rate",
         "hide": false,
         "id": "5",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per gNodeB N3 Inbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate inbound bitrate traffic on N3 interface per gNodeB over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_gnb_n3_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_gnb_n3_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_gnb_n3_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_gnb_n3_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per gNodeB N3 Outbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate outbound bitrate traffic on N3 interface per gNodeB over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_gnb_n3_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_gnb_n3_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_gnb_n3_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_gnb_n3_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "N3 Inbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate inbound bitrate traffic on N3 interface over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_n3_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_n3_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_n3_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_n3_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "N3 Outbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate outbound bitrate traffic on N3 interface over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_n3_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_n3_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_n3_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_n3_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "N3 Inbound Packet Rate",
     "type": "timeseries",
     "description": "Aggregate inbound packet rate traffic on N3 interface over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_n3_inbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_n3_inbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_n3_inbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_n3_inbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "N3 Outbound Packet Rate",
     "type": "timeseries",
     "description": "Aggregate outbound packet rate traffic on N3 interface over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_n3_outbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_n3_outbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_n3_outbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_n3_outbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per DNN N6 Inbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate inbound bitrate traffic on N6 interface per DNN over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_dnn_n6_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_dnn_n6_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_dnn_n6_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_dnn_n6_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per DNN N6 Outbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate outbound bitrate traffic on N6 interface per DNN over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_dnn_n6_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_dnn_n6_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_dnn_n6_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_dnn_n6_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per DNN N6 Inbound Packet Rate",
     "type": "timeseries",
     "description": "Aggregate inbound packet rate traffic on N6 interface per DNN over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_dnn_n6_inbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_dnn_n6_inbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_dnn_n6_inbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_dnn_n6_inbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per DNN N6 Outbound Packet Rate",
     "type": "timeseries",
     "description": "Aggregate outbound packet rate traffic on N6 interface per DNN over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_dnn_n6_outbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_dnn_n6_outbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_dnn_n6_outbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_dnn_n6_outbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per 5QI N3 Inbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate inbound bitrate traffic on N3 per 5QI over last 5 mins",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_5qi_n3_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_5qi_n3_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_5qi_n3_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_5qi_n3_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per 5QI N3 Outbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate outbound bitrate traffic on N3 per 5QI over last 5 mins",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 189 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_5qi_n3_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_5qi_n3_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_5qi_n3_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_5qi_n3_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per 5QI N3 Inbound Packet Loss",
     "type": "timeseries",
     "description": "Aggregate inbound packet loss rate on N3 interface per 5QI over last 5 mins",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_5qi_n3_inbound_packet_loss",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_5qi_n3_inbound_packet_loss:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_5qi_n3_inbound_packet_loss",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_5qi_n3_inbound_packet_loss:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per 5QI N3 Outbound Packet Loss",
     "type": "timeseries",
     "description": "Aggregate outbound packet loss rate on N3 interface per 5QI over last 5 mins",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_5qi_n3_outbound_packet_loss",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_5qi_n3_outbound_packet_loss:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_5qi_n3_outbound_packet_loss",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_5qi_n3_outbound_packet_loss:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per 5QI N3 Packets Disorder",
     "type": "timeseries",
     "description": "Aggregate number of out-of-order packets received on N3 per 5QI over last 5 mins",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_5qi_n3_packet_disorder",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_5qi_n3_packet_disorder:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_5qi_n3_packet_disorder",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_5qi_n3_packet_disorder:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Slice Trafic KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Slice N3 Inbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate inbound bitrate traffic on N3 per S-NSSAI over last 5 mins",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_slice_n3_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_slice_n3_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_slice_n3_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_slice_n3_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per Slice N3 Outbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate outbound bitrate traffic on N3 per S-NSSAI over last 5 mins",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 225 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_slice_n3_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_slice_n3_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_slice_n3_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_slice_n3_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per Slice N3 Inbound Packet Rate",
     "type": "timeseries",
     "description": "Aggregate inbound packet rate traffic on N3 interface per S-NSSAI over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 232 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_slice_n3_inbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_slice_n3_inbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_slice_n3_inbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_slice_n3_inbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per Slice N3 Outbound Packet Rate",
     "type": "timeseries",
     "description": "Aggregate outbound packet rate traffic on N3 interface per S-NSSAI over last 5 mins.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 239 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_slice_n3_outbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_slice_n3_outbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_slice_n3_outbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_5g_slice_n3_outbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "QOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "QOS Create Request",
     "type": "timeseries",
     "description": "This KPI provides the number of QoS flows requested to create per SNSSAI and 5QI. ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 579 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_create_req",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_create_req",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "QOS Create Success",
     "type": "timeseries",
     "description": "This KPI provides the number of QoS flows successfully created per SNSSAI and 5QI.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 586 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_create_succ",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_create_succ",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "QOS Create Fail",
     "type": "timeseries",
     "description": "This KPI provides the number of QoS flows failed to create for each SNSSAI and 5QI. ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 593 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_create_fail",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_create_fail",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "QOS Modify Request",
     "type": "timeseries",
     "description": "This KPI provides the number of QoS flows requested to modify per SNSSAI and 5QI. ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 600 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_mod_req",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_mod_req",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "QOS Modify Success",
     "type": "timeseries",
     "description": "This KPI provides the number of QoS flows successfully modified per SNSSAI and 5QI. ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 607 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_mod_succ",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_mod_succ",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "QOS Modify Failure",
     "type": "timeseries",
     "description": "This KPI provides the number of QoS flows failed to modify for each SNSSAI and 5QI. ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 614 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_mod_fail",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_mod_fail",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Mean QOS Flows",
     "type": "timeseries",
     "description": "This KPI provides the mean number of QoS flows at the SMF per SNSSAI and 5QI",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 621 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_nbr_mean",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_nbr_mean",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Peak QOS Flows",
     "type": "timeseries",
     "description": "This KPI provides the peak number of QoS flows at the SMF per SNSSAI and 5QI",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 628 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_nbr_peak",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Max",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_qos_nbr_peak",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "pm_data_source.dn.keyword:*FIVEQI* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$snssai",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Attempted N4 Session Modifications",
     "type": "timeseries",
     "description": "This KPI provides the number of attempted N4 session modifications",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 635 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_n4_mod_req",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_n4_mod_req",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Failed N4 Session Modifications",
     "type": "timeseries",
     "description": "This KPI provides the number of failed N4 session modifications",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 642 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_n4_mod_fail",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_n4_mod_fail",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Attempted N4 Session Deletions",
     "type": "timeseries",
     "description": "This KPI provides the number of attempted N4 session deletions",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 649 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_n4_del_req",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_n4_del_req",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Failed N4 Session Deletions",
     "type": "timeseries",
     "description": "This KPI provides the number of failed N4 session deletions",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 656 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_n4_del_fail",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_n4_del_fail",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "PCF",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "SM Policy Association Request",
     "type": "timeseries",
     "description": "This KPI provides the number of SM policy association requests received by the PCF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9508 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pa_policy_sm_asso_req",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pa_policy_sm_asso_req",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "SM Policy Association Success",
     "type": "timeseries",
     "description": "This KPI provides the number of successful SM policy associations at the PCF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9515 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pa_policy_sm_asso_succ",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pa_policy_sm_asso_succ",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "SM Policy Association Update Request",
     "type": "timeseries",
     "description": "This KPI provides the number of SM policy association update requests received by the PCF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9522 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pcf_policy_sm_assoc_update_req",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pcf_policy_sm_assoc_update_req",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "SM Policy Association Update Success",
     "type": "timeseries",
     "description": "This KPI provides the number of successful update of SM policy association on PCF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9529 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pcf_policy_sm_assoc_update_succ",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pcf_policy_sm_assoc_update_succ",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "SM Policy Association Update Notification Request",
     "type": "timeseries",
     "description": "This KPI provides the number of SM policy association update notify requests PCF sends to SMF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9536 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pcf_policy_sm_assoc_notif_req",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pcf_policy_sm_assoc_notif_req",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "SM Policy Association Update Notification Success",
     "type": "timeseries",
     "description": "This KPI provides the number of successful update notifies of SM policy association on PCF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9543 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pcf_policy_sm_assoc_notif_succ",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_pcf_policy_sm_assoc_notif_succ",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Session Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "PDU Session Mean",
     "type": "timeseries",
     "description": "This KPI provides the mean number of PDU sessions per SNSSAI",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1755 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_nbr_mean",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Average",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_nbr_mean",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDU Session Max",
     "type": "timeseries",
     "description": "This KPI provides the max number of PDU sessions per SNSSAI",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1762 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_nbr_max",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_nbr_max",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "SMF PDU Creation Request",
     "type": "timeseries",
     "description": "This KPI provides the number of PDU sessions requested to be created by the SMF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1769 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_create_req",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_create_req",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "SMF PDU Creation Success",
     "type": "timeseries",
     "description": "This KPI provides the number of PDU sessions successfully created by the SMF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1776 },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_create_succ",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_create_succ",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "SMF PDU Creation Failure",
     "type": "timeseries",
     "description": "This measurement provides the number of PDU sessions failed to be created by the SMF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1783 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_create_fail",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_create_fail",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDU Session Establishment Mean Time",
     "type": "timeseries",
     "description": "This KPI provides the mean time of PDU session establishment during each granularity period per SNSSAI",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1790 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_time_mean",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_time_mean",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDU Session Establishment Max Time",
     "type": "timeseries",
     "description": "This measurement provides the max time of PDU session establishment during each granularity period per SNSSAI",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1797 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "{{pm_data_source.dn.keyword}}/{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.dn.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_time_max",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_time_max",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn.keyword:*SNSSAI* AND pm_data_source.dn:$snssai NOT pm_data_source.dn.keyword:*FIVEQI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDU Session Modification Request",
     "type": "timeseries",
     "description": "This KPI provides the number of PDU session modification requests sent by the SMF to AMF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1804 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_mod_smfinit_req",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_mod_smfinit_req",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDU Session Modification Success",
     "type": "timeseries",
     "description": "This KPI provides the number of successful PDU session modifications acknowledged by the SMF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1811 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_mod_smfinit_succ",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_mod_smfinit_succ",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDU Session Modification Failures",
     "type": "timeseries",
     "description": "This KPI provides the number of failed PDU session modifications responded by the SMF",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1818 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_mod_smfinit_fail",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_5g_sm_pdus_mod_smfinit_fail",
         "hide": false,
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  }
 ]
}