{
 "title": "Nokia DAC CORE 4G PM KPI",
 "tags": [ "CorePM" ],
 "time": { "from": "now-24h", "to": "now-15m" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "grafana-opensearch-datasource" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "5m,15m,1h,3h,6h,12h,1d,7d,15d,1M"
   }
  ]
 },
 "panels": [
  {
   "title": "UL Throughput",
   "type": "stat",
   "description": "Uplink Throughput (outbound bitrate on SGI interface)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_4g_apn_sgi_outbound_bitrate",
       "hide": false,
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_4g_apn_sgi_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "DL throughput",
   "type": "stat",
   "description": "Downlink Throughput (outbound bitrate on S1U interface)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_4g_s1u_outbound_bitrate",
       "hide": false,
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_4g_s1u_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "UE throughput UL",
   "type": "stat",
   "description": "UE throughput  on uplink",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_ue_ul_bitrate",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_ue_ul_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "UE throughput DL",
   "type": "stat",
   "description": "UE throughput  on downlink",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_ue_dl_bitrate",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_ue_dl_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Registered UEs",
   "type": "stat",
   "description": "Current Number of Registered UEs",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_4g_data_emm_registered_ues",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_4g_data_emm_registered_ues:* AND pm_data_source.nhg_alias.keyword:$nhgname",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Active UEs",
   "type": "stat",
   "description": "Current Number of UEs in EMMREGISTERED+ECMCONNECTED states",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_mcn_4g_data_active_ues",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data.ndac_rr_mcn_4g_data_active_ues:* AND pm_data_source.nhg_alias.keyword:$nhgname",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Traffic KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per eNodeB Inbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate inbound bitrate traffic on S1U interface per eNodeB over last 5 mins.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_enb_s1u_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_enb_s1u_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_enb_s1u_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_enb_s1u_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per eNodeB Outbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate outbound bitrate traffic on S1U interface per eNodeB over last 5 mins",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_enb_s1u_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_enb_s1u_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_enb_s1u_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_enb_s1u_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "S1U Inbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate inbound bitrate traffic sent on S1U interface over 5 mins.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_s1u_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_s1u_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_s1u_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_s1u_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "S1U Outbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate outbound bitrate traffic sent on S1U interface over 5 mins.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_s1u_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_s1u_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_s1u_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_s1u_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "S1U Inbound Packets Rate",
     "type": "timeseries",
     "description": "Aggregate inbound packets sent per second on S1U interface over 5 mins.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_s1u_inbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_s1u_inbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_s1u_inbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_s1u_inbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "S1U Outbound Packets Rate",
     "type": "timeseries",
     "description": "Aggregate outbound packets sent per second on S1U interface over 5 mins.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_s1u_outbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_s1u_outbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_s1u_outbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_s1u_outbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per APN SGI Inbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate inbound bitrate traffic sent per APN on SGI interface over 5 mins.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_apn_sgi_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_apn_sgi_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_apn_sgi_inbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_apn_sgi_inbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per APN SGI Outbound Bitrate",
     "type": "timeseries",
     "description": "Aggregate outbound bitrate traffic sent per APN on SGI interface over 5 mins.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_apn_sgi_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_apn_sgi_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_apn_sgi_outbound_bitrate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_apn_sgi_outbound_bitrate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per APN SGI Inbound Packets Rate",
     "type": "timeseries",
     "description": "Aggregate inbound packet rate traffic sent per APN on SGI interface over 5 mins.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_apn_sgi_inbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_apn_sgi_inbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_apn_sgi_inbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_apn_sgi_inbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Per APN SGI Outbound Packets Rate",
     "type": "timeseries",
     "description": "Aggregate outbound packet rate traffic sent per APN on SGI interface over 5 mins.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_apn_sgi_outbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_apn_sgi_outbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_apn_sgi_outbound_packet_rate",
         "hide": false,
         "id": "3",
         "type": "sum"
        }
       ],
       "query": "pm_data.ndac_rr_mcn_4g_apn_sgi_outbound_packet_rate:* AND pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "UE throughput UL",
     "type": "timeseries",
     "description": "UE throughput  on uplink",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_ue_ul_bitrate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_ue_ul_bitrate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "UE throughput DL",
     "type": "timeseries",
     "description": "UE throughput  on downlink",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_ue_dl_bitrate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_ue_dl_bitrate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "UE throughput - Per IMSI",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 77 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.timestamp",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_ue_ul_bitrate",
         "id": "1",
         "type": "sum"
        },
        {
         "field": "pm_data.ndac_rr_mcn_ue_dl_bitrate",
         "hide": false,
         "id": "5",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*IMSI*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "SGW Control KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active bearers",
     "type": "timeseries",
     "description": "Current Number of Active Bearers",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_active_bearers",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_active_bearers",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Active pdn sessions",
     "type": "timeseries",
     "description": "Current Number of Active PDN Sessions",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_active_pdn_sessions",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_active_pdn_sessions",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Num of Data PDN Conn Requests",
     "type": "timeseries",
     "description": "Number of received data Create Session Requests",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_pdn_conn_requests",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_pdn_conn_requests",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Data PDN Conn Success",
     "type": "timeseries",
     "description": "Number of Successful Data PDN Connection over last 5 min",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_pdn_conn_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_pdn_conn_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Data PDN Conn Success Rate",
     "type": "timeseries",
     "description": "Number of Successful Data PDN Connectivity procedures per second.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_pdn_conn_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_pdn_conn_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDN Conn Requests",
     "type": "timeseries",
     "description": "Number of requested PDN Connection over last 5 mins",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_pdn_conn_success",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "sum"
        },
        {
         "field": "pm_data.ndac_rr_mcn_4g_pdn_conn_failure",
         "hide": true,
         "id": "4",
         "type": "sum"
        },
        {
         "id": "5",
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "1" },
          { "name": "var2", "pipelineAgg": "4" }
         ],
         "settings": { "script": "params.var1+params.var2" },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_pdn_conn_success",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "sum"
        },
        {
         "field": "pm_data.ndac_rr_mcn_4g_pdn_conn_failure",
         "hide": true,
         "id": "3",
         "type": "sum"
        },
        {
         "id": "4",
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "1" },
          { "name": "var2", "pipelineAgg": "3" }
         ],
         "settings": { "script": "params.var1+params.var2" },
         "type": "bucket_script"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDN Conn Success",
     "type": "timeseries",
     "description": "Number of Successful PDN Connection over last 5 mins",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_pdn_conn_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_pdn_conn_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDN Conn Failures",
     "type": "timeseries",
     "description": "Number of Failed PDN Connection over last 5 mins",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_pdn_conn_failure",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_pdn_conn_failure",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "PDN Conn Success Ratio",
     "type": "timeseries",
     "description": "Successful PDN Connection ratio over last 5 mins",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_pdn_conn_success_ratio",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_pdn_conn_success_ratio",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Failed EPS attach procedures",
     "type": "timeseries",
     "description": "This KPI provides Failed EPS attach procedures due to EPS service not allowed",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_attach_reject_eps_srv_not_allowed",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_4g_attach_reject_eps_srv_not_allowed:*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_attach_reject_eps_srv_not_allowed",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_4g_attach_reject_eps_srv_not_allowed:*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Number of Failed UE Secondary Authentication Attempts",
     "type": "timeseries",
     "description": "Number of Failed UE Secondary Authentication Attempts per APN",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_pgw_auth_failed_apn",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_4g_pgw_auth_failed_apn:*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_pgw_auth_failed_apn",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_4g_pgw_auth_failed_apn:*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Mean number of Framed Routes Established",
     "type": "timeseries",
     "description": "Mean number of Framed Routes Established per APN",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}/{{pm_data_source.dn.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pm_data_source.dn.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_upf_num_framed_routes_apn",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_4g_upf_num_framed_routes_apn:*",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_upf_num_framed_routes_apn",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data.ndac_rr_mcn_4g_upf_num_framed_routes_apn:*",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "MME KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num of attach requests",
     "type": "timeseries",
     "description": "Number of UE Attach Requests",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_attach_requests",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_attach_requests",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Num of attach success",
     "type": "timeseries",
     "description": "Number of Successful UE Attaches",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_attach_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_attach_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Num of attach success rate",
     "type": "timeseries",
     "description": "Number of Successful UE Attaches per second",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_attach_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_attach_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Num of registered UEs",
     "type": "timeseries",
     "description": "Current Number of Registered UEs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_emm_registered_ues",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_emm_registered_ues",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Num of active UEs",
     "type": "timeseries",
     "description": "Current Number of UEs in EMMREGISTERED+ECMCONNECTED states",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_active_ues",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_active_ues",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Ho_x2_attempts",
     "type": "timeseries",
     "description": "Number of UE X2 Handover Requests",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 193 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_x2_attempts",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_x2_attempts",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Ho_x2_success",
     "type": "timeseries",
     "description": "Number of Successful X2 Handovers",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 199 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_x2_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_x2_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "X2 HO success rate",
     "type": "timeseries",
     "description": "Number of Successful X2 Handovers per second",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_x2_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_x2_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Ho_S1_attempts",
     "type": "timeseries",
     "description": "Number of processed S1 Handover Required messages",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 211 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_s1_attempts",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_s1_attempts",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Ho_S1_success",
     "type": "timeseries",
     "description": "Number of Successful S1 Handovers",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_s1_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_s1_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "S1 HO success rate",
     "type": "timeseries",
     "description": "Number of Successful S1 Handovers per second",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_s1_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_ho_s1_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "TAU requests",
     "type": "timeseries",
     "description": "Number of UE Tracking Area Update Requests",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 229 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_tau_requests",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_tau_requests",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "TAU success",
     "type": "timeseries",
     "description": "Number of Successful UE Tracking Area Updates",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 235 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_tau_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_tau_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "TAU success rate",
     "type": "timeseries",
     "description": "Number of Successful UE Tracking Area Updates per second.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 241 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_tau_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_tau_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Paging Requests",
     "type": "timeseries",
     "description": "Number of UE Psdomain Paging Requests",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 247 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_paging_ps_requests",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_paging_ps_requests",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Paging Success",
     "type": "timeseries",
     "description": "Number of Successful UE PS-domain Paging Requests",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_paging_ps_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_paging_ps_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Paging Success rate",
     "type": "timeseries",
     "description": "Number of Successful UE PS-domain Paging Requests per second.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_paging_ps_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_paging_ps_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Bearer addition attempts",
     "type": "timeseries",
     "description": "Number of started Dedicated Bearer Addition procedures",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 265 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_bearer_add_attempts",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_bearer_add_attempts",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Bearer addition success",
     "type": "timeseries",
     "description": "Number of Successful Dedicated Bearer Addition procedures",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 271 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_bearer_add_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_bearer_add_success",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Bearer addition success rate",
     "type": "timeseries",
     "description": "Number of Successful Dedicated Bearer Addition procedures per second.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 277 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_bearer_add_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_data_bearer_add_success_rate",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "3GPP KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "EPS attach success rate",
     "type": "timeseries",
     "description": "This KPI describes the ratio of the number of successfully performed EPS attach procedures to the number of attempted EPS attach procedures for EPC network and is used to evaluate accessibility provided by EPS and network performance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 284 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_eps_attach_success_rate",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Dedicated EPS Bearer Creation Success Rate",
     "type": "timeseries",
     "description": "This KPI describes the ratio of the number of successfully performed dedicated EPS bearer creation procedures by PGW to the number of attempted dedicated EPS bearer creation procedures by PGW and is used to evaluate service availability provided by EPS and network performance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_dedicated_eps_bearer_creation_success_rate",
         "hide": false,
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    },
    {
     "title": "Tracking Area Update Success Rate",
     "type": "timeseries",
     "description": "This KPI describes the ratio of the number of successfully performed tracking area update procedures to the number of attempted tracking area update procedures and is used to evaluate mobility provided by EPS and network performance.\n",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{pm_data_source.nhg_alias.keyword}}",
       "bucketAggs": [
        {
         "field": "pm_data_source.nhg_alias.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "pm_data.ndac_rr_mcn_4g_tracking_area_update_success_rate",
         "hide": false,
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "pm_data_source.nhg_alias.keyword:$nhgname",
       "timeField": "pm_data_source.timestamp"
      }
     ]
    }
   ]
  }
 ]
}