{
 "title": "Nokia DAC Radio 5G PM KPI - Slice aware scheduling KPIs",
 "tags": [ "Radio5G" ],
 "time": { "from": "now-24h", "to": "now-15m" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "grafana-opensearch-datasource" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "slice_id",
    "label": "Slice ID",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.slice_id.keyword\", \"query\":\"pm_data_source.nhg_alias.keyword:$nhgname\", \"size\": 10000}"
   },
   {
    "name": "ap_id",
    "label": "Access Point ID",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.dn.keyword\", \"query\":\"pm_data_source.nhg_alias.keyword:$nhgname AND (pm_data_source.dn:*NRCEL* OR pm_data_source.dn:*NRBTS*)\", \"size\": 10000}"
   },
   {
    "name": "groupby",
    "label": "Object Level",
    "query": "gNB : pm_data_source.hw_id.keyword, Cell : pm_data_source.dn.keyword"
   },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "15m,30m,1h,3h,6h,12h,1d,7d,15d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "NR_5965a 5G Maximum utilization ratio of PDSCH PRBs per cell per resource group [%]",
   "type": "timeseries",
   "description": "This KPI shows the maximum utilization ratio of PDSCH PRBs per cell per resource group.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.NCUPNRG_M55910C00002",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.NCUPNRG_M55910C00002",
       "hide": true,
       "id": "30",
       "type": "max"
      },
      {
       "id": "31",
       "pipelineVariables": [
        { "name": "am55910c00002", "pipelineAgg": "3" },
        { "name": "m55910c00002", "pipelineAgg": "30" }
       ],
       "settings": {
        "script": "if (params.am55910c00002 == null) { return null } else { return params.m55910c00002 }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*NRRESOURCEGROUP* AND pm_data.NCUPNRG_M55910C00002:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "NR_5966a 5G Maximum utilization ratio of PUSCH PRBs per cell per resource group [%]",
   "type": "timeseries",
   "description": "This KPI shows the maximum utilization ratio of PUSCH PRBs per cell per resource group.\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.NCUPNRG_M55910C00004",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.NCUPNRG_M55910C00004",
       "hide": true,
       "id": "30",
       "type": "max"
      },
      {
       "id": "31",
       "pipelineVariables": [
        { "name": "am55910c00004", "pipelineAgg": "3" },
        { "name": "m55910c00004", "pipelineAgg": "30" }
       ],
       "settings": {
        "script": "if (params.am55910c00004 == null) { return null } else { return params.m55910c00004 }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*NRRESOURCEGROUP* AND pm_data.NCUPNRG_M55910C00004:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "NR_6127a 5G Average utilization of PDSCH PRBs for slice-aware traffic per cell per resource group [%]",
   "type": "timeseries",
   "description": "This KPI shows the average utilization of PDSCH PRBs for slice-aware traffic per cell per resource group.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.NCUPNRG_M55910C00001",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.NCUPNRG_M55910C00001",
       "hide": true,
       "id": "30",
       "type": "sum"
      },
      {
       "field": "pm_data.NCUPNRG_M55910C00028",
       "hide": true,
       "id": "32",
       "type": "sum"
      },
      {
       "hide": false,
       "id": "33",
       "pipelineVariables": [
        { "name": "am55910c00001", "pipelineAgg": "3" },
        { "name": "m55910c00001", "pipelineAgg": "30" },
        { "name": "m55910c00028", "pipelineAgg": "32" }
       ],
       "settings": {
        "script": "if (params.am55910c00001 == null) { return null } else if (params.m55910c00001 == 0) { return 0 } else { return 100*(params.m55910c00001/params.m55910c00028) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*NRRESOURCEGROUP* AND pm_data.NCUPNRG_M55910C00001:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "NR_6128a 5G Average utilization of PUSCH PRBs for slice-aware traffic per cell per resource group [%]",
   "type": "timeseries",
   "description": "This KPI shows the average utilization of PUSCH PRBs for slice-aware traffic per cell per resource group.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.NCUPNRG_M55910C00003",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.NCUPNRG_M55910C00003",
       "hide": true,
       "id": "30",
       "type": "sum"
      },
      {
       "field": "pm_data.NCUPNRG_M55910C00027",
       "hide": true,
       "id": "32",
       "type": "sum"
      },
      {
       "hide": false,
       "id": "33",
       "pipelineVariables": [
        { "name": "am55910c00003", "pipelineAgg": "3" },
        { "name": "m55910c00003", "pipelineAgg": "30" },
        { "name": "m55910c00027", "pipelineAgg": "32" }
       ],
       "settings": {
        "script": "if (params.am55910c00003 == null) { return null } else if (params.m55910c00003 == 0) { return 0 } else { return 100*(params.m55910c00003/params.m55910c00027) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*NRRESOURCEGROUP* AND pm_data.NCUPNRG_M55910C00003:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  }
 ]
}