{
 "title": "NDAC EDGE PM KPI",
 "tags": [ "EdgePM" ],
 "time": { "from": "now-24h", "to": "now-15m" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "grafana-opensearch-datasource" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "edgealias",
    "label": "Slice ID",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.edge_alias.keyword\", \"query\":\"pm_data_source.nhg_alias.keyword:$nhgname\"}"
   },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1m,5m,15m,1h,3h,6h,12h,1d,7d,15d,1M"
   }
  ]
 },
 "panels": [
  {
   "title": "NDAC Edge CPU Usage [%]",
   "type": "gauge",
   "description": "This KPI provides the usage of the CPU of the edge node is percentage. ",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU Usage",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_cpu_usage_percentage",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge disk temperature [°C]",
   "type": "gauge",
   "description": "This KPI provides the temperature of the hard disk on the edge node in degree celsius .",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_disk_temp_celsius",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias AND pm_data.ndac_rr_edge_disk_temp_celsius\n:* ",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge RAM usage [%]",
   "type": "stat",
   "description": "This KPI provides the usage of the RAM memory usage of the edge node in percentage.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Ram Usage",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_ram_usage_percentage",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge disk usage [%]",
   "type": "stat",
   "description": "This KPI provides the usage of hard disk of the edge node in percentage.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Memory Usage",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_disk_usage_percentage",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias AND pm_data.ndac_rr_edge_disk_usage_percentage:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge CPU Usage [%]",
   "type": "timeseries",
   "description": "This KPI provides the usage of the CPU of the edge node is percentage. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Average CPU Usage",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_cpu_usage_percentage",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias",
     "timeField": "pm_data_source.timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.edge_alias.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_cpu_usage_percentage",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge disk temperature [°C]",
   "type": "timeseries",
   "description": "This KPI provides the temperature of the hard disk on the edge node in degree celsius .",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Average Disk Temp",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_disk_temp_celsius",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias AND pm_data.ndac_rr_edge_disk_temp_celsius\n:* ",
     "timeField": "pm_data_source.timestamp"
    },
    {
     "alias": "{{pm_data_source.edge_alias.keyword}}/{{pm_data_source.dn.keyword}}",
     "bucketAggs": [
      {
       "field": "pm_data_source.edge_alias.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pm_data_source.dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_disk_temp_celsius",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias AND pm_data.ndac_rr_edge_disk_temp_celsius\n:* ",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge RAM usage [%]",
   "type": "timeseries",
   "description": "This KPI provides the usage of the RAM memory usage of the edge node in percentage.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Average Ram Usage",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_ram_usage_percentage",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias",
     "timeField": "pm_data_source.timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.edge_alias.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_ram_usage_percentage",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge disk usage [%]",
   "type": "timeseries",
   "description": "This KPI provides the usage of hard disk of the edge node in percentage.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Average Memory Usage",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_disk_usage_percentage",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias AND pm_data.ndac_rr_edge_disk_usage_percentage:*",
     "timeField": "pm_data_source.timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.edge_alias.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "$agg" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_disk_usage_percentage",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias AND pm_data.ndac_rr_edge_disk_usage_percentage:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  }
 ]
}