{
 "title": "NDAC EDGE PM KPI",
 "tags": [ "EdgePM" ],
 "time": { "from": "now-24h", "to": "now-15m" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "dataSource", "label": "Data Source", "query": "elasticsearch" },
   {
    "name": "edgealias",
    "label": "Edge Alias",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.edge_alias.keyword\"}"
   },
   {
    "name": "nhgid",
    "label": "NHG Id",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.nhg_id.keyword\", \"query\":\"pm_data_source.edge_alias.keyword:$edgealias\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "NDAC Edge CPU Usage",
   "type": "gauge",
   "description": "This KPI provides the usage of the CPU of the edge node is percentage. ",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU Usage",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_cpu_usage_percentage",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge disk temperature",
   "type": "gauge",
   "description": "This KPI provides the temperature of the hard disk on the edge node in degree celsius .",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_disk_temp_celsius",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias AND pm_data.ndac_rr_edge_disk_temp_celsius\n:* ",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge RAM usage ",
   "type": "stat",
   "description": "This KPI provides the usage of the RAM memory usage of the edge node in percentage.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Ram Usage",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_ram_usage_percentage",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge disk usage",
   "type": "stat",
   "description": "This KPI provides the usage of hard disk of the edge node in percentage.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Memory Usage",
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_disk_usage_percentage",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias AND pm_data.ndac_rr_edge_disk_usage_percentage:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge CPU Usage",
   "type": "timeseries",
   "description": "This KPI provides the usage of the CPU of the edge node is percentage. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU Usage",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_cpu_usage_percentage",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge disk temperature",
   "type": "timeseries",
   "description": "This KPI provides the temperature of the hard disk on the edge node in degree celsius .",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_disk_temp_celsius",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias AND pm_data.ndac_rr_edge_disk_temp_celsius\n:* ",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge RAM usage ",
   "type": "timeseries",
   "description": "This KPI provides the usage of the RAM memory usage of the edge node in percentage.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Ram Usage",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_ram_usage_percentage",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "NDAC Edge disk usage",
   "type": "timeseries",
   "description": "This KPI provides the usage of hard disk of the edge node in percentage.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Memory Usage",
     "bucketAggs": [
      {
       "field": "pm_data_source.dn.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.ndac_rr_edge_disk_usage_percentage",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "pm_data_source.edge_alias.keyword:$edgealias AND pm_data.ndac_rr_edge_disk_usage_percentage:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  }
 ]
}