{
 "title": "NDAC Radio 4G PM KPI - Dashboard",
 "tags": [ "Radio4G" ],
 "time": { "from": "now-24h", "to": "now-15m" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "dataSource", "label": "Data Source", "query": "elasticsearch" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "ap_id",
    "label": "Access Point ID",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.dn.keyword\", \"query\":\"pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:*LNCEL*\"}"
   },
   {
    "name": "groupby",
    "label": "Object Level",
    "query": "pm_data_source.hw_id.keyword,pm_data_source.dn.keyword"
   }
  ]
 },
 "panels": [
  {
   "title": "Cell Availability",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C3",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C6",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C3",
       "hide": true,
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "8",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8020C3", "pipelineAgg": "3" },
        { "name": "M8020C6", "pipelineAgg": "4" },
        { "name": "avc3", "pipelineAgg": "6" }
       ],
       "settings": {
        "script": "if (params.avc3 == null) { return null }  else if (params.M8020C6 == 0) { return 0 } else { return 100*(params.M8020C3/params.M8020C6) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Avail_M8020C3:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "Cells UP",
   "type": "stat",
   "description": "Displays the number of cells up in the selected network",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.end_timestamp",
       "id": "2",
       "settings": { "interval": "15m", "min_doc_count": 0, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C3",
       "id": "9",
       "inlineScript": "doc['pm_data.LTE_Cell_Avail_M8020C3'].size()",
       "meta": {},
       "settings": {
        "script": {
         "inline": "doc['pm_data.LTE_Cell_Avail_M8020C3'].size()"
        }
       },
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND -pm_data.LTE_Cell_Avail_M8020C3:0",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "Average and Max PDCP datarate UL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "Avg PDCP Throughput UL",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C23",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C23:*",
     "timeField": "pm_data_source.end_timestamp"
    },
    {
     "alias": "Maximum PDCP Throughput UL",
     "bucketAggs": [
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C22",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C22:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "Average and Max PDCP datarate DL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "Avg PDCP Throughput DL",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C26",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C26:*",
     "timeField": "pm_data_source.end_timestamp"
    },
    {
     "alias": "Maximum PDCP Throughput DL",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C25",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C25:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "Total PCDP Datarate UL",
   "type": "stat",
   "description": "The measurement gives indication of the eUu interface traffic load by reporting Mean UL PDCP traffic throughput.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg PDCP Throughput UL",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pm_data_source.nhg_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C23",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C23:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "Active UE quantity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_UE_Quantity_M8051C58",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_Quantity_M8051C58",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "8",
       "meta": {},
       "pipelineVariables": [
        { "name": "av_58", "pipelineAgg": "4" },
        { "name": "C58", "pipelineAgg": "3" }
       ],
       "settings": {
        "script": "if (params.av_58 == null) { return null } else { return params.C58 }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_UE_Quantity_M8051C58:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "Cells DOWN",
   "type": "stat",
   "description": "Displays the number of cells down in the selected network",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pm_data_source.end_timestamp",
       "id": "2",
       "settings": { "interval": "15m", "min_doc_count": 0, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C3",
       "id": "9",
       "inlineScript": "doc['pm_data.LTE_Cell_Avail_M8020C3'].size()",
       "meta": {},
       "settings": {
        "script": {
         "inline": "doc['pm_data.LTE_Cell_Avail_M8020C3'].size()"
        }
       },
       "type": "sum"
      }
     ],
     "query": "(pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL*) AND (pm_data.LTE_Cell_Avail_M8020C3:0 OR pm_data.LTE_Cell_Avail_M8020C6:0)",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "Total PCDP Datarate DL",
   "type": "stat",
   "description": "The measurement gives indication of the eUu interface traffic load by reporting Mean DL PDCP traffic throughput.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg PDCP Throughput DL",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pm_data_source.nhg_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C26",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C26:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5750a E-UTRAN Cell Availability Ratio",
   "type": "graph",
   "description": "This KPI shows the ratio of services in a cell being available for end users.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C3",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C6",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C3",
       "hide": true,
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "9",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8020C3", "pipelineAgg": "1" },
        { "name": "M8020C6", "pipelineAgg": "4" },
        { "name": "avc3", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "if (params.avc3 == null) { return null }  else if (params.M8020C6 == 0) { return 0 } else { return 100*(params.M8020C3/params.M8020C6) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Avail_M8020C3:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "M8051C58 - E-UTRAN LTE_UE_Quantity",
   "type": "graph",
   "description": "E-UTRAN LTE_UE_Quantity_M8051C58\n",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_UE_Quantity_M8051C58",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_Quantity_M8051C58",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "5",
       "meta": {},
       "pipelineVariables": [
        { "name": "av_58", "pipelineAgg": "4" },
        { "name": "C58", "pipelineAgg": "1" }
       ],
       "settings": {
        "script": "if (params.av_58 == null) { return null } else { return params.C58 }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_UE_Quantity_M8051C58:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_6160b Total E-UTRAN RRC Connection Setup Attempts",
   "type": "graph",
   "description": "The KPI shows the number of attempts for the elementary procedure \"RRC connection establishment\" used to set up a radio connection from UE to eNB (involves SRB1 establishment).",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_UE_State_M8013C17",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C17",
       "hide": true,
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C18",
       "hide": true,
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C19",
       "hide": true,
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C34",
       "hide": true,
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C31",
       "hide": true,
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C21",
       "hide": true,
       "id": "11",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C93",
       "hide": true,
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C91",
       "hide": true,
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "14",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8013C17", "pipelineAgg": "1" },
        { "name": "M8013C18", "pipelineAgg": "7" },
        { "name": "M8013C19", "pipelineAgg": "8" },
        { "name": "M8013C34", "pipelineAgg": "9" },
        { "name": "M8013C31", "pipelineAgg": "10" },
        { "name": "M8013C21", "pipelineAgg": "11" },
        { "name": "M8013C93", "pipelineAgg": "12" },
        { "name": "M8013C91", "pipelineAgg": "13" },
        { "name": "AV_C17", "pipelineAgg": "5" }
       ],
       "settings": {
        "script": "if (params.AV_C17 == null) { return null } else { return (params.M8013C17 + params.M8013C18 +params.M8013C19 +params.M8013C34 +params.M8013C31 +params.M8013C21 +params.M8013C93 +params.M8013C91) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_UE_State_M8013C17:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5118a E-UTRAN E-RAB Setup Attempts",
   "type": "graph",
   "description": "The KPI indicates the number of E-RAB setup attempts.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C0",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C0",
       "hide": true,
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "6",
       "meta": {},
       "pipelineVariables": [
        { "name": "c0", "pipelineAgg": "1" },
        { "name": "av_6c0", "pipelineAgg": "5" }
       ],
       "settings": {
        "script": "if (params.av_6c0 == null) { return null } else { return params.c0 }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_EPS_Bearer_M8006C0:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5143a Total E-UTRAN RRC Connection Re-establishment Success Ratio",
   "type": "graph",
   "description": "The KPI shows the setup success ratio for the RRC connection re-establishment procedure. The procedure is used in case of a failure situation (such as a radio or handover failure) to keep the UE in an LTE RRC_CONNECTED state and continue the RRC connection without going to an RRC_IDLE state.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_RRC_M8008C5",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_RRC_M8008C4",
       "hide": true,
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_RRC_M8008C5",
       "hide": true,
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "8",
       "meta": {},
       "pipelineVariables": [
        { "name": "c5", "pipelineAgg": "1" },
        { "name": "c4", "pipelineAgg": "5" },
        { "name": "av_c5", "pipelineAgg": "7" }
       ],
       "settings": {
        "script": "if (params.av_c5 == null) { return null } else if (params.c4 == 0){ return 0 } else { return 100*(params.c5/params.c4) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_RRC_M8008C5:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5116a E-UTRAN Data Radio Bearer Attempts",
   "type": "graph",
   "description": "The KPI shows the Data Radio Bearer Setup Attempts.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pm_data_source.end_timestamp", "id": "2", "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Radio_Bearer_M8007C0",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Radio_Bearer_M8007C0",
       "hide": true,
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "6",
       "meta": {},
       "pipelineVariables": [
        { "name": "c0", "pipelineAgg": "1" },
        { "name": "av_c0", "pipelineAgg": "5" }
       ],
       "settings": {
        "script": "if (params.av_c0 == null) { return null } else { return params.c0 }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Radio_Bearer_M8007C0:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE 5242b E-Utran Average RRC Connected UEs",
   "type": "graph",
   "description": "This KPI shows the average number of UEs having one SRB during the measurement period.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_UE_Quantity_M8051C60",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_Quantity_M8051C61",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_Quantity_M8051C60",
       "hide": true,
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "9",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8051C60", "pipelineAgg": "1" },
        { "name": "M8051C61", "pipelineAgg": "4" },
        { "name": "AV_60", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "if (params.AV_60 == null) { return null }  else if (params.M8051C61 == 0) { return 0 } else { return (params.M8051C60/params.M8051C61) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_UE_Quantity_M8051C61:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE 5212a E-Utran PDCP SDU Volume DL ",
   "type": "graph",
   "description": "This KPI shows the PDCP SDU volume on an eUu interface per cell in a downlink direction.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C20",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C20",
       "hide": true,
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "9",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8012C20", "pipelineAgg": "4" },
        { "name": "AV_C20", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "if (params.AV_C20 == null) { return null }  else { return (params.M8012C20/1000000) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C20:*",
     "timeField": "pm_data_source.end_timestamp"
    },
    {
     "alias": "Total volume",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "7",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C20",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C20",
       "hide": true,
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "9",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8012C20", "pipelineAgg": "4" },
        { "name": "AV_C20", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "if (params.AV_C20 == null) { return null }  else { return (params.M8012C20/1000000) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C20:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE 5213a E-Utran PDCP SDU Volume UL",
   "type": "graph",
   "description": "This KPI shows the PDCP SDU volume on an eUu interface per cell in an uplink direction.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C19",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C19",
       "hide": true,
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "9",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8012C19", "pipelineAgg": "4" },
        { "name": "AV_C19", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "if (params.AV_C19 == null) { return null }  else { return (params.M8012C19/1000000) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C19:*",
     "timeField": "pm_data_source.end_timestamp"
    },
    {
     "alias": "Total volume",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "7",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C19",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C19",
       "hide": true,
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "9",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8012C19", "pipelineAgg": "4" },
        { "name": "AV_C19", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "if (params.AV_C19 == null) { return null }  else { return (params.M8012C19/1000000) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C19:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "Average PDCP Layer Throughput UL",
   "type": "graph",
   "description": "The measurement gives indication of the eUu interface traffic load by reporting Mean UL PDCP traffic throughput.\nThis counter is updated when a PDCP SDU is received from UE.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C23",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C23:*",
     "timeField": "pm_data_source.end_timestamp"
    },
    {
     "alias": "Total Avg PDCP Datarate UL",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C23",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C23:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "Average PDCP Layer Throughput DL",
   "type": "graph",
   "description": "The measurement gives indication of the eUu interface traffic load by reporting Mean DL PDCP traffic throughput.\nThis counter is updated when a PDCP SDU is transmitted towards the UE.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C26",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C26:*",
     "timeField": "pm_data_source.end_timestamp"
    },
    {
     "alias": "Total Avg PDCP Datarate DL",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C26",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C26:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE 6159a E-Utran RACH Setup Attempts",
   "type": "graph",
   "description": "This KPI describes the total number of RA preambles.\nBoth contention based and dedicated preambles are considered within the KPI.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Load_M8001C6",
       "hide": true,
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.LTE_Cell_Load_M8001C7",
       "hide": true,
       "id": "10",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8001C6", "pipelineAgg": "4" },
        { "name": "AV_C6", "pipelineAgg": "8" }
       ],
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Load_M8001C286",
       "hide": true,
       "id": "11",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Load_M8001C6",
       "hide": true,
       "id": "12",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "13",
       "meta": {},
       "pipelineVariables": [
        { "name": "AV_C6", "pipelineAgg": "8" },
        { "name": "M8001C7", "pipelineAgg": "10" },
        { "name": "M8001C286", "pipelineAgg": "11" },
        { "name": "M8001C6", "pipelineAgg": "12" }
       ],
       "settings": {
        "script": "if (params.AV_C6 == null) { return null }  else { return (params.M8001C6 + params.M8001C7 + params.M8001C286) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Load_M8001C6:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE 5218g Total E-UTRAN RRC Connection Setup Success Ratio",
   "type": "graph",
   "description": "The KPI shows the setup success ratio for the elementary procedure \"RRC connection establishment\" used to set up a radio connection from UE to eNB (involves SRB1 establishment) .",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_UE_State_M8013C5",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C17",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C18",
       "hide": true,
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C19",
       "hide": true,
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C34",
       "hide": true,
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C31",
       "hide": true,
       "id": "11",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C21",
       "hide": true,
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C93",
       "hide": true,
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C91",
       "hide": true,
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_UE_State_M8013C5",
       "hide": true,
       "id": "15",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "16",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8013C5", "pipelineAgg": "1" },
        { "name": "M8013C17", "pipelineAgg": "4" },
        { "name": "M8013C18", "pipelineAgg": "8" },
        { "name": "M8013C19", "pipelineAgg": "9" },
        { "name": "M8013C34", "pipelineAgg": "10" },
        { "name": "M8013C31", "pipelineAgg": "11" },
        { "name": "M8013C21", "pipelineAgg": "12" },
        { "name": "M8013C93", "pipelineAgg": "13" },
        { "name": "M8013C91", "pipelineAgg": "14" },
        { "name": "AV_C5", "pipelineAgg": "15" }
       ],
       "settings": {
        "script": "if (params.AV_C5 == null) { return null } else if ( (params.M8013C17 + params.M8013C18 +params.M8013C19 +params.M8013C34 +params.M8013C31 +params.M8013C21 +params.M8013C93 +params.M8013C91) == 0) { return 0 } else { return 100 * ((params.M8013C5)/(params.M8013C17 + params.M8013C18 +params.M8013C19 +params.M8013C34 +params.M8013C31 +params.M8013C21 +params.M8013C93 +params.M8013C91)) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_UE_State_M8013C5:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5025i E-UTRAN E-RAB Drop Ratio, RAN View",
   "type": "graph",
   "description": "This KPI describes the ratio of abnormally released (dropped) E-RABs from RAN point of view.\nEach bearer of the Bearer to be Released List IE is counted. RAN point of view means that as abnormal E-RAB drops only those ones initiated by eNB are counted.E-RAB releases due to pre-emption initiated by eNB are counted as normal releases as they are not real drops resulted from any radio quality problems. In denominator of the formula normal E-RAB releases due to successful HO to eHRPD are not counted.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "3",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C261",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C254",
       "hide": true,
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C255",
       "hide": true,
       "id": "10",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8006C185", "pipelineAgg": "4" },
        { "name": "AV_C185", "pipelineAgg": "8" }
       ],
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C258",
       "hide": true,
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C341",
       "hide": true,
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C301",
       "hide": true,
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C309",
       "hide": true,
       "id": "15",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C311",
       "hide": true,
       "id": "16",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C313",
       "hide": true,
       "id": "17",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C254",
       "hide": true,
       "id": "18",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C261",
       "hide": true,
       "id": "19",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C6",
       "hide": true,
       "id": "20",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C7",
       "hide": true,
       "id": "21",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C8",
       "hide": true,
       "id": "22",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C9",
       "hide": true,
       "id": "23",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C277",
       "hide": true,
       "id": "24",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C301",
       "hide": true,
       "id": "25",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C303",
       "hide": true,
       "id": "26",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C306",
       "hide": true,
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C309",
       "hide": true,
       "id": "28",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C310",
       "hide": true,
       "id": "29",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C311",
       "hide": true,
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C312",
       "hide": true,
       "id": "31",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C313",
       "hide": true,
       "id": "32",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C261",
       "hide": true,
       "id": "33",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "34",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8006C261", "pipelineAgg": "4" },
        { "name": "M8006C254", "pipelineAgg": "8" },
        { "name": "M8006C255", "pipelineAgg": "10" },
        { "name": "M8006C258", "pipelineAgg": "12" },
        { "name": "M8006C341", "pipelineAgg": "13" },
        { "name": "M8006C301", "pipelineAgg": "14" },
        { "name": "M8006C309", "pipelineAgg": "15" },
        { "name": "M8006C311", "pipelineAgg": "16" },
        { "name": "M8006C313", "pipelineAgg": "17" },
        { "name": "M8006C254", "pipelineAgg": "8" },
        { "name": "M8006C261", "pipelineAgg": "4" },
        { "name": "M8006C6", "pipelineAgg": "20" },
        { "name": "M8006C7", "pipelineAgg": "21" },
        { "name": "M8006C8", "pipelineAgg": "22" },
        { "name": "M8006C9", "pipelineAgg": "23" },
        { "name": "M8006C277", "pipelineAgg": "24" },
        { "name": "M8006C301", "pipelineAgg": "14" },
        { "name": "M8006C303", "pipelineAgg": "26" },
        { "name": "M8006C306", "pipelineAgg": "27" },
        { "name": "M8006C309", "pipelineAgg": "15" },
        { "name": "M8006C310", "pipelineAgg": "29" },
        { "name": "M8006C311", "pipelineAgg": "16" },
        { "name": "M8006C312", "pipelineAgg": "31" },
        { "name": "M8006C313", "pipelineAgg": "17" },
        { "name": "AV_C261", "pipelineAgg": "33" }
       ],
       "settings": {
        "script": "if (params.AV_C261 == null) { return null }  else if ((params.M8006C254 + params.M8006C261 + params.M8006C6 + params.M8006C7 + params.M8006C8 + params.M8006C9 + params.M8006C277 - params.M8006C301 + params.M8006C303 + params.M8006C306 + params.M8006C309 + params.M8006C310 + params.M8006C311 + params.M8006C312 + params.M8006C313) == 0) { return 0 } else { return 100*((params.M8006C261 + params.M8006C254 - params.M8006C255 - params.M8006C258 - params.M8006C341 - params.M8006C301 + params.M8006C309 + params.M8006C311 + params.M8006C313)/(params.M8006C254 + params.M8006C261 + params.M8006C6 + params.M8006C7 + params.M8006C8 + params.M8006C9 + params.M8006C277 - params.M8006C301 + params.M8006C303 + params.M8006C306 + params.M8006C309 + params.M8006C310 + params.M8006C311 + params.M8006C312 + params.M8006C313)) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_EPS_Bearer_M8006C261:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5017a\tE-UTRAN E-RAB Setup Success Ratio",
   "type": "graph",
   "description": "The KPI indicates the setup success ratio of the elementary E-RAB setup procedure, used to set up the E-RAB between MME and UE.\nIt shows the E-UTRAN's contribution to network accessibility for the end user, not the whole end-to-end service accessibility.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "15",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C0",
       "hide": true,
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C1",
       "hide": true,
       "id": "17",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_EPS_Bearer_M8006C0",
       "hide": true,
       "id": "18",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "19",
       "meta": {},
       "pipelineVariables": [
        { "name": "Avg_C0", "pipelineAgg": "14" },
        { "name": "M8006C1", "pipelineAgg": "17" },
        { "name": "M8006C0", "pipelineAgg": "18" }
       ],
       "settings": {
        "script": "if ( params.Avg_C0 == null ) { return null } else if ( params.M8006C0 == 0 ) { return 0 } else { return 100*(params.M8006C1/params.M8006C0) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_EPS_Bearer_M8006C0:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_6161a\tRRC Connection Re-establishment Attempts per type total attempts",
   "type": "graph",
   "description": "The KPI shows the RRC Connection Re-establishment Attempts per type, e.g. total, due to \"HandoverFailure\", due to \"otherFailure\" or due to \"reconfigFailure\".",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "15",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_RRC_M8008C4",
       "hide": true,
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.LTE_RRC_M8008C4",
       "hide": true,
       "id": "17",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "19",
       "meta": {},
       "pipelineVariables": [
        { "name": "Avg_C4", "pipelineAgg": "14" },
        { "name": "M8008C4", "pipelineAgg": "17" }
       ],
       "settings": {
        "script": "if ( params.Avg_C4 == null ) { return null } else { return params.M8008C4}"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_RRC_M8008C4:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5276b\tE-UTRAN average PRB usage per TTI DL / E-UTRAN Avg PRB usage per TTI DL",
   "type": "graph",
   "description": "This KPI shows the average value of the physical resource block (PRB) utilization per TTI in a downlink direction. The utilization is defined by the ratio of used to available PRBs per TTI.\nThe monitoring also includes almost blank subframes (ABSs) for the cells that are configured as macro ones in the eICIC partnership.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "15",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Resource_M8011C37",
       "hide": true,
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.LTE_Cell_Resource_M8011C37",
       "hide": true,
       "id": "17",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "19",
       "meta": {},
       "pipelineVariables": [
        { "name": "Avg_C37", "pipelineAgg": "14" },
        { "name": "M8011C37", "pipelineAgg": "17" }
       ],
       "settings": {
        "script": "if ( params.Avg_C37 == null ) { return null } else { return params.M8011C37/10 }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Resource_M8011C37:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5273b\tE-UTRAN Average PRB usage per TTI UL",
   "type": "graph",
   "description": "This KPI shows the average value of the physical resource block (PRB) utilization per TTI in an uplink direction. The utilization is defined by the ratio of used to available PRBs per TTI.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "15",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Resource_M8011C24",
       "hide": true,
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.LTE_Cell_Resource_M8011C24",
       "hide": true,
       "id": "17",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "19",
       "meta": {},
       "pipelineVariables": [
        { "name": "Avg_C24", "pipelineAgg": "14" },
        { "name": "M8011C24", "pipelineAgg": "17" }
       ],
       "settings": {
        "script": "if ( params.Avg_C24 == null ) { return null } else { return params.M8011C24/10 }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Resource_M8011C24:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5427b\tE-UTRAN Average CQI",
   "type": "graph",
   "description": "This KPI shows the average UE reported Channel\nQuality Indicator (CQI) value.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "15",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C36",
       "hide": true,
       "id": "17",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C37",
       "hide": true,
       "id": "19",
       "meta": {},
       "pipelineVariables": [
        { "name": "Avg_C37", "pipelineAgg": "14" },
        { "name": "M8011C37", "pipelineAgg": "17" }
       ],
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C38",
       "hide": true,
       "id": "20",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C39",
       "hide": true,
       "id": "21",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C40",
       "hide": true,
       "id": "22",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C41",
       "hide": true,
       "id": "23",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C42",
       "hide": true,
       "id": "24",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C43",
       "hide": true,
       "id": "25",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C44",
       "hide": true,
       "id": "26",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C45",
       "hide": true,
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C46",
       "hide": true,
       "id": "28",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C47",
       "hide": true,
       "id": "29",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C48",
       "hide": true,
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C49",
       "hide": true,
       "id": "31",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C50",
       "hide": true,
       "id": "32",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C51",
       "hide": true,
       "id": "33",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "34",
       "meta": {},
       "pipelineVariables": [
        { "name": "c36", "pipelineAgg": "17" },
        { "name": "c37", "pipelineAgg": "19" },
        { "name": "c38", "pipelineAgg": "20" },
        { "name": "c39", "pipelineAgg": "21" },
        { "name": "c40", "pipelineAgg": "22" },
        { "name": "c41", "pipelineAgg": "23" },
        { "name": "c42", "pipelineAgg": "24" },
        { "name": "c43", "pipelineAgg": "25" },
        { "name": "c44", "pipelineAgg": "26" },
        { "name": "c45", "pipelineAgg": "27" },
        { "name": "c46", "pipelineAgg": "28" },
        { "name": "c47", "pipelineAgg": "29" },
        { "name": "c48", "pipelineAgg": "30" },
        { "name": "c49", "pipelineAgg": "31" },
        { "name": "c50", "pipelineAgg": "32" },
        { "name": "c51", "pipelineAgg": "33" },
        { "name": "c116", "pipelineAgg": "35" },
        { "name": "c117", "pipelineAgg": "36" },
        { "name": "c118", "pipelineAgg": "37" },
        { "name": "c119", "pipelineAgg": "38" },
        { "name": "c120", "pipelineAgg": "39" },
        { "name": "c121", "pipelineAgg": "40" },
        { "name": "c122", "pipelineAgg": "41" },
        { "name": "c123", "pipelineAgg": "42" },
        { "name": "c124", "pipelineAgg": "43" },
        { "name": "c125", "pipelineAgg": "44" },
        { "name": "c126", "pipelineAgg": "45" },
        { "name": "c127", "pipelineAgg": "46" },
        { "name": "c128", "pipelineAgg": "47" },
        { "name": "c129", "pipelineAgg": "48" },
        { "name": "c130", "pipelineAgg": "49" },
        { "name": "c131", "pipelineAgg": "50" }
       ],
       "settings": {
        "script": "if ((params.c36 + params.c116 + params.c37 + params.c117 + params.c38 + params.c118 + params.c39 + params.c119 + params.c40 + params.c120 + params.c41 + params.c121 + params.c42 + params.c122 + params.c43 + params.c123 + params.c44 + params.c124 + params.c45 + params.c125 + params.c46 + params.c126 + params.c47 + params.c127 + params.c48 + params.c128 + params.c49 + params.c129 + params.c50 + params.c130 + params.c51 + params.c131) == 0) { return 0 } else { return (1*(params.c37 + params.c117) + 2*(params.c38 + params.c118) + 3*(params.c39 + params.c119) + 4*(params.c40 + params.c120) + 5*(params.c41 + params.c121) + 6*(params.c42 + params.c122) + 7*(params.c43 + params.c123) + 8*(params.c44 + params.c124) + 9*(params.c45 + params.c125) + 10*(params.c46 + params.c126) + 11*(params.c47 + params.c127) + 12*(params.c48 + params.c128) + 13*(params.c49 + params.c129) + 14*(params.c50 + params.c130) + 15*(params.c51 + params.c131))/(params.c36 + params.c116 + params.c37 + params.c117 + params.c38 + params.c118 + params.c39 + params.c119 + params.c40 + params.c120 + params.c41 + params.c121 + params.c42 + params.c122 + params.c43 + params.c123 + params.c44 + params.c124 + params.c45 + params.c125 + params.c46 + params.c126 + params.c47 + params.c127 + params.c48 + params.c128 + params.c49 + params.c129 + params.c50 + params.c130 + params.c51 + params.c131) }"
       },
       "type": "bucket_script"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C116",
       "hide": true,
       "id": "35",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C117",
       "hide": true,
       "id": "36",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C118",
       "hide": true,
       "id": "37",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C119",
       "hide": true,
       "id": "38",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C120",
       "hide": true,
       "id": "39",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C121",
       "hide": true,
       "id": "40",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C122",
       "hide": true,
       "id": "41",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C123",
       "hide": true,
       "id": "42",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C124",
       "hide": true,
       "id": "43",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C125",
       "hide": true,
       "id": "44",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C126",
       "hide": true,
       "id": "45",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C127",
       "hide": true,
       "id": "46",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C128",
       "hide": true,
       "id": "47",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C129",
       "hide": true,
       "id": "48",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C130",
       "hide": true,
       "id": "49",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Pwr_and_Qual_DL_M8010C131",
       "hide": true,
       "id": "50",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Pwr_and_Qual_DL_M8010C36:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5114a\tE-UTRAN Inter-Frequency HO Success Ratio",
   "type": "graph",
   "description": "This KPI indicates the success ratio for the inter-frequency HO when the source eNB receives information that the UE is successfully connected to the target cell within the target eNB. The KPI is defined independently of network topology (intra-eNB HO/inter-eNB HO) and of the usage of measurement gaps.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "15",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Handover_M8021C2",
       "hide": true,
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "pm_data.LTE_Handover_M8021C2",
       "hide": true,
       "id": "17",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Handover_M8021C0",
       "hide": true,
       "id": "19",
       "meta": {},
       "pipelineVariables": [
        { "name": "Avg_C20", "pipelineAgg": "14" },
        { "name": "M8012C20", "pipelineAgg": "17" },
        { "name": "M8051C101", "pipelineAgg": "20" }
       ],
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Handover_M8021C0",
       "id": "20",
       "meta": {},
       "pipelineVariables": [
        { "name": "Avg_c2", "pipelineAgg": "14" },
        { "name": "M8021C2", "pipelineAgg": "17" },
        { "name": "M8021C0", "pipelineAgg": "19" }
       ],
       "settings": {
        "script": "if ( params.Avg_c2 == null ) { return null } else if ( params.M8021C0 == 0 ) { return 0 } else { return 100*(params.M8021C2/params.M8021C0) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Handover_M8021C2:*",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  },
  {
   "title": "LTE_5568a\tE-UTRAN Intra-Frequency HO Success Ratio",
   "type": "graph",
   "description": "This KPI indicates attempts at an intra-frequency HO when the source eNB receives information that the UE is successfully connected to the target cell. The KPI is defined independently of  network topology (intra-eNB HO/inter-eNB HO).",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$groupby",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pm_data_source.end_timestamp",
       "id": "15",
       "settings": { "interval": "15m", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Intra_eNB_HO_M8009C7",
       "hide": true,
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Inter_eNB_HO_M8014C7",
       "hide": true,
       "id": "17",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Inter_eNB_HO_M8014C19",
       "hide": true,
       "id": "19",
       "meta": {},
       "pipelineVariables": [
        { "name": "Avg_C20", "pipelineAgg": "14" },
        { "name": "M8012C20", "pipelineAgg": "17" },
        { "name": "M8051C101", "pipelineAgg": "20" }
       ],
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Handover_M8021C2",
       "hide": true,
       "id": "20",
       "meta": {},
       "pipelineVariables": [
        { "name": "Avg_c2", "pipelineAgg": "14" },
        { "name": "M8021C2", "pipelineAgg": "17" },
        { "name": "M8021C0", "pipelineAgg": "19" }
       ],
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Intra_eNB_HO_M8009C6",
       "hide": true,
       "id": "21",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Inter_eNB_HO_M8014C6",
       "hide": true,
       "id": "22",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Inter_eNB_HO_M8014C18",
       "hide": true,
       "id": "23",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Handover_M8021C0",
       "hide": true,
       "id": "24",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "25",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8009C7", "pipelineAgg": "14" },
        { "name": "M8014C7", "pipelineAgg": "17" },
        { "name": "M8014C19", "pipelineAgg": "19" },
        { "name": "M8021C2", "pipelineAgg": "20" },
        { "name": "M8009C6", "pipelineAgg": "21" },
        { "name": "M8014C6", "pipelineAgg": "22" },
        { "name": "M8014C18", "pipelineAgg": "23" },
        { "name": "M8021C0", "pipelineAgg": "24" }
       ],
       "settings": {
        "script": "if ( (params.M8009C6 + params.M8014C6 + params.M8014C18 - params.M8021C0) == 0 ) { return 0 } else { return 100*(params.M8009C7 + params.M8014C7 + params.M8014C19 - params.M8021C2)/(params.M8009C6 + params.M8014C6 +params.M8014C18 - params.M8021C0) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$nhgname AND pm_data_source.dn:$ap_id AND pm_data_source.dn:*LNCEL* AND (pm_data.LTE_Intra_eNB_HO_M8009C7:* OR pm_data.LTE_Inter_eNB_HO_M8014C7:* OR pm_data.LTE_Handover_M8021C2:*)",
     "timeField": "pm_data_source.end_timestamp"
    }
   ]
  }
 ]
}