{
 "title": "NDAC FM Alarms Active Dashboard",
 "description": "NDAC FM Active alarms dashboard",
 "tags": [
  "DACAlarms",
  "DACActiveAlarms"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "elasticsearch" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data_source.nhg_alias.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "NDAC FM ACTIVE ALARMS DASHBOARD",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Critical Alarms",
   "type": "stat",
   "description": "Provides the count of critical alarms",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:CRITICAL",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Major Alarms",
   "type": "stat",
   "description": "Provides the count of major alarms",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:MAJOR",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Minor Alarms",
   "type": "stat",
   "description": "Provides the count of minor alarms",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgnameAND fm_data.severity:MINOR",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Warning Alarms",
   "type": "stat",
   "description": "Provides the count of warning alarms",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:WARNING",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": " Critical Active Alarms",
   "type": "table",
   "description": "This table will show all active alarms that are critical across all edges enodeB's\n\nNote: Turnoff the refresh timer when moving to different page.",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 5000 },
       "type": "raw_document"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:CRITICAL",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": " Major Active Alarms",
   "type": "table",
   "description": "This table will show all active alarms that are major across all edges enodeB's\n\nNote: Turnoff the refresh timer when moving to different page.",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 5000 },
       "type": "raw_document"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:MAJOR",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": " Minor Active Alarms",
   "type": "table",
   "description": "This table will show all active alarms that are minor across all edges enodeB's\n\nNote: Turnoff the refresh timer when moving to different page.",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 5000 },
       "type": "raw_document"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname  AND fm_data.severity:MINOR",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": " Warning Active Alarms",
   "type": "table",
   "description": "This table will show all active alarms that are warning across all edges enodeB's\n\nNote: Turnoff the refresh timer when moving to different page.",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 5000 },
       "type": "raw_document"
      }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$nhgname AND fm_data.severity:WARNING",
     "timeField": "fm_data.event_time"
    }
   ]
  }
 ]
}