{
 "title": "NDAC Overview",
 "time": { "from": "now-24h", "to": "now-30m" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "networkIdentifier", "label": "Identifier for network regex", "query": "CHANGE_THIS" },
   { "name": "radio_fm_dataSource", "query": "elasticsearch" },
   {
    "name": "radio_fm_nhgname",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data_source.nhg_alias.keyword\"}"
   },
   { "name": "pm_dataSource", "query": "elasticsearch" },
   {
    "name": "pm_nhgname",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "pm_apId",
    "query": "{\"find\": \"terms\", \"field\": \"pm_data_source.dn.keyword\", \"query\":\"pm_data_source.nhg_alias.keyword:$pm_nhgname\"}"
   },
   { "name": "ndac_fm_dataSource", "query": "elasticsearch" },
   {
    "name": "ndac_fm_nhgname",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data_source.nhg_alias.keyword\"}"
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download Throughput",
   "type": "graph",
   "description": "This is the average download seen per cell of the LTE network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "Average",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C26",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$pm_nhgname AND pm_data_source.dn:$pm_apId AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C25:*",
     "timeField": "pm_data_source.timestamp"
    },
    {
     "alias": "Maximum",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C25",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$pm_nhgname AND pm_data_source.dn:$pm_apId AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C25:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Upload Throughput",
   "type": "graph",
   "description": "This is the average upload seen per cell of the LTE network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "Average",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C23",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$pm_nhgname AND pm_data_source.dn:$pm_apId AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C25:*",
     "timeField": "pm_data_source.timestamp"
    },
    {
     "alias": "Maximum",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Throughput_M8012C22",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$pm_nhgname AND pm_data_source.dn:$pm_apId AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Throughput_M8012C25:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Cell Availability",
   "type": "graph",
   "description": "This shows the uptime of LTE cells. If this is not showing at 100% there might be an issue with one of the cells and performance will be degraded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Percentage of cells available",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C3",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C6",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "pm_data.LTE_Cell_Avail_M8020C3",
       "hide": true,
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "6",
       "meta": {},
       "pipelineVariables": [
        { "name": "M8020C3", "pipelineAgg": "3" },
        { "name": "M8020C6", "pipelineAgg": "4" },
        { "name": "avc3", "pipelineAgg": "5" }
       ],
       "settings": {
        "script": "if (params.avc3 == null) { return null }  else if (params.M8020C6 == 0) { return 0 } else { return 100*(params.M8020C3/params.M8020C6) }"
       },
       "type": "bucket_script"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$pm_nhgname AND pm_data_source.dn:$pm_apId AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_Cell_Avail_M8020C3:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  {
   "title": "Active UEs",
   "type": "graph",
   "description": "This is the amount of connected LTE CPE devices such as Industrial CPE's, Tablets, ...",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Amount of UEs",
     "bucketAggs": [
      { "field": "pm_data_source.timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pm_data.LTE_UE_Quantity_M8051C58",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "pm_data_source.nhg_alias.keyword:$pm_nhgname AND pm_data_source.dn:$pm_apId AND pm_data_source.dn:*LNCEL* AND pm_data.LTE_UE_Quantity_M8051C58:*",
     "timeField": "pm_data_source.timestamp"
    }
   ]
  },
  { "title": "Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Radio Active Critical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$radio_fm_nhgname AND fm_data.severity:critical",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "NDAC Active Critical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$ndac_fm_nhgname AND fm_data.severity:critical",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Radio Active Major",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$radio_fm_nhgname AND fm_data.severity:major",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "NDAC Active Major",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$ndac_fm_nhgname AND fm_data.severity:major",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Radio Active Minor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$radio_fm_nhgname AND fm_data.severity:minor",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "NDAC Active Minor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$ndac_fm_nhgname AND fm_data.severity:minor",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Radio Active Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$radio_fm_nhgname AND fm_data.severity:warning",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "NDAC Active Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data.alarm_state:ACTIVE AND fm_data_source.nhg_alias.keyword:$ndac_fm_nhgname AND fm_data.severity:warning",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Radio History Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 5000 },
       "type": "raw_data"
      }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$radio_fm_nhgname AND NOT fm_data.severity:cleared",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "NDAC History Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 5000 },
       "type": "raw_data"
      }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$ndac_fm_nhgname",
     "timeField": "fm_data.event_time"
    }
   ]
  }
 ]
}