{
 "title": "NDAC Radio FM Alarms History Dashboard",
 "description": "NDAC FM History alarms dashboard",
 "tags": [
  "HistoryAlarmDashboard",
  "RadioAlarms"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "elasticsearch" },
   {
    "name": "nhgname",
    "label": "Network Hw Group Name",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data_source.nhg_alias.keyword\"}"
   },
   {
    "name": "apid",
    "label": "Access Point ID",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data_source.dn.keyword\", \"query\":\"fm_data_source.nhg_alias.keyword:$nhgname\"}"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "{\"find\": \"terms\", \"field\": \"fm_data.severity.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "NDAC FM HISTORY ALARMS DASHBOARD",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Critical Alarms",
   "type": "stat",
   "description": "Provides the count of critical alarms",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:critical",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Major Alarms",
   "type": "stat",
   "description": "Provides the count of major alarms",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 2 },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:major",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Minor Alarms",
   "type": "stat",
   "description": "Provides the count of minor alarms",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 2 },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:minor",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Warning Alarms",
   "type": "stat",
   "description": "Provides the count of warning alarms",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 2 },
   "targets": [
    {
     "alias": "Critical",
     "bucketAggs": [
      {
       "field": "fm_data.severity.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:warning",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "Cleared Alarms",
   "type": "stat",
   "description": "Provides the count of cleared alarms",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fm_data.alarm_state.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.alarm_state:CLEARED  or fm_data.severity:cleared",
     "timeField": "fm_data.event_time"
    }
   ]
  },
  {
   "title": "History Alarms",
   "type": "table",
   "description": "This table will show all alarms history across all edges enodeB's",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "fm_data_source.nhg_alias.keyword:$nhgname AND fm_data_source.dn:$apid AND fm_data.severity:$severity",
     "timeField": "fm_data.event_time"
    }
   ]
  }
 ]
}